import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { compareSpecificity, compilePath } from './path'

/**
 * `@cascivo/app/vite` — file-based routes, as a generated file rather than a virtual module.
 *
 * `src/routes/**` is scanned into `src/routes.gen.ts`: one `lazyRoute` per file, most
 * specific first, plus an `AppPath` union of every pattern. Because the output is a real
 * file, TypeScript, editors and code review see it like any other module, and the plugin
 * can disappear from the build without the app noticing.
 *
 * | File                       | Path             |
 * | -------------------------- | ---------------- |
 * | `index.tsx`                | `/`              |
 * | `settings.tsx`             | `/settings`      |
 * | `settings/index.tsx`       | `/settings`      |
 * | `c/[id].tsx`               | `/c/:id`         |
 * | `files/[...path].tsx`      | `/files/*`       |
 * | `404.tsx`                  | not-found route  |
 *
 * Files and folders starting with `_`, and `*.test.*` / `*.spec.*`, are not routes.
 */

export interface RouteFile {
  /** Path relative to the routes directory, `/`-separated, with extension. */
  file: string
  /** The route pattern, or `null` for the not-found route. */
  path: string | null
}

const ROUTE_EXTENSION = /\.(tsx|jsx)$/

/** The pattern a route file serves, `null` for `404`, or `undefined` if it is not a route. */
export function fileToRoutePath(file: string): string | null | undefined {
  if (!ROUTE_EXTENSION.test(file) || /\.(test|spec)\.[jt]sx$/.test(file)) return undefined
  const segments = file.replace(ROUTE_EXTENSION, '').split('/')
  if (segments.some((s) => s.startsWith('_'))) return undefined
  if (segments.length === 1 && segments[0] === '404') return null
  if (segments.at(-1) === 'index') segments.pop()
  const pattern = segments.map((segment, i) => {
    const splat = /^\[\.\.\.[A-Za-z_$][\w$]*\]$/.test(segment)
    if (splat) {
      if (i !== segments.length - 1) {
        throw new Error(`routes/${file}: a [...rest] segment must be last`)
      }
      return '*'
    }
    const param = /^\[([A-Za-z_$][\w$]*)\]$/.exec(segment)
    if (param) return `:${param[1]}`
    if (/[[\]]/.test(segment)) throw new Error(`routes/${file}: malformed segment "${segment}"`)
    return segment
  })
  return `/${pattern.join('/')}`
}

/** Every route file under `dir`, as `/`-separated relative paths. */
export function scanRoutes(dir: string): string[] {
  if (!existsSync(dir)) return []
  const out: string[] = []
  const walk = (current: string) => {
    for (const entry of readdirSync(current).sort()) {
      const full = join(current, entry)
      if (statSync(full).isDirectory()) walk(full)
      else out.push(relative(dir, full).split(sep).join('/'))
    }
  }
  walk(dir)
  return out
}

/**
 * The source of `routes.gen.ts` for a list of route files. Pure: the same files always
 * produce byte-identical output, so the file only changes when the routes do.
 *
 * @param importPrefix - the routes directory relative to the generated file, e.g. `./routes`.
 */
export function generateRoutes(files: readonly string[], importPrefix: string): string {
  const routes: RouteFile[] = []
  const seen = new Map<string | null, string>()
  for (const file of files) {
    const path = fileToRoutePath(file)
    if (path === undefined) continue
    const clash = seen.get(path)
    if (clash) {
      throw new Error(`routes/${clash} and routes/${file} both define ${path ?? 'the 404 route'}`)
    }
    seen.set(path, file)
    routes.push({ file, path })
  }

  const specifier = (file: string) => `${importPrefix}/${file.replace(ROUTE_EXTENSION, '')}`
  const ordered = routes
    .filter((r): r is RouteFile & { path: string } => r.path !== null)
    .map((r) => ({ ...r, compiled: compilePath(r.path) }))
    .sort((a, b) => compareSpecificity(a.compiled, b.compiled) || a.path.localeCompare(b.path))
  const notFound = routes.find((r) => r.path === null)

  const lines = [
    '// Generated by @cascivo/app/vite from the routes directory — do not edit.',
    '// Add, rename or delete a route file and this file is rewritten.',
    "import { lazyRoute } from '@cascivo/app'",
    "import type { Route } from '@cascivo/app'",
    '',
    'export const routes: Route[] = [',
    ...ordered.map((r) => `  lazyRoute('${r.path}', () => import('${specifier(r.file)}')),`),
    ']',
    '',
    notFound
      ? `export const notFound: Route | undefined = lazyRoute('*', () => import('${specifier(notFound.file)}'))`
      : 'export const notFound: Route | undefined = undefined',
    '',
    '/** Every route pattern. Fill one with `buildPath` for a typed link. */',
    `export type AppPath = ${ordered.length > 0 ? ordered.map((r) => `'${r.path}'`).join(' | ') : 'never'}`,
    '',
  ]
  return lines.join('\n')
}

export interface CascivoRoutesOptions {
  /** Directory of route files, relative to the Vite root. Default `src/routes`. */
  dir?: string
  /** Generated file, relative to the Vite root. Default `src/routes.gen.ts`. */
  out?: string
}

/**
 * The slice of Vite's plugin API this uses, declared structurally so the published types
 * do not depend on a particular Vite version.
 */
export interface CascivoRoutesPlugin {
  name: string
  enforce: 'pre'
  configResolved(config: { root: string }): void
  buildStart(): void
  configureServer(server: {
    watcher: {
      add(path: string): unknown
      on(event: string, listener: (file: string) => void): unknown
    }
  }): void
}

/**
 * Generates `src/routes.gen.ts` from `src/routes/**` at startup and whenever a route file
 * is added or removed. Writes only when the content changes, so it never loops HMR.
 */
export function cascivoRoutes(options: CascivoRoutesOptions = {}): CascivoRoutesPlugin {
  let root = process.cwd()
  const dir = () => resolve(root, options.dir ?? 'src/routes')
  const out = () => resolve(root, options.out ?? 'src/routes.gen.ts')

  function write(): void {
    let prefix = relative(dirname(out()), dir()).split(sep).join('/')
    if (!prefix.startsWith('.')) prefix = `./${prefix}`
    const source = generateRoutes(scanRoutes(dir()), prefix)
    const current = existsSync(out()) ? readFileSync(out(), 'utf8') : null
    if (current !== source) writeFileSync(out(), source)
  }

  return {
    name: 'cascivo:routes',
    enforce: 'pre',
    configResolved(config) {
      root = config.root
    },
    buildStart() {
      write()
    },
    configureServer(server) {
      server.watcher.add(dir())
      const onChange = (file: string) => {
        if (resolve(file).startsWith(dir() + sep)) write()
      }
      server.watcher.on('add', onChange)
      server.watcher.on('unlink', onChange)
    },
  }
}
