packages:
  - 'packages/*'
  - 'apps/*'
  - 'apps/examples/*'

catalogMode: prefer

catalog:
  '@types/node': ^24
  '@types/react': ^18
  '@types/react-dom': ^18
  '@preact/signals-react': ^2
  preact: ^10
  react: ^18
  react-dom: ^18
  typescript: ^5
  vite-plus: ^0.1.24

overrides:
  vite: 'npm:@voidzero-dev/vite-plus-core@latest'
  vitest: 'npm:@voidzero-dev/vite-plus-test@latest'
