/**
 * Generates `apps/site/src/shims/*.d.ts` — the type shims the docs site compiles against.
 *
 * ## Why shims exist at all
 *
 * `apps/site` is Preact (`jsxImportSource: preact`); the components are React. Pointing
 * tsconfig at the component *sources* makes `tsc` check their JSX bodies under Preact's
 * attribute types, which fails on the signal bindings the components rely on
 * (`Signalish<string | undefined>` is not assignable to Preact's `string | false | 0 | null`).
 * So the site cannot compile against the sources, and `tsconfig.json` maps every
 * `@cascivo/components/*` specifier here instead.
 *
 * ## Why these are generated
 *
 * Hand-written, they were a second copy of the public API that only a human kept in sync, and
 * at 1.0 they went stale: `dropdown.d.ts` still declared the removed `separator` flag, six
 * more still declared the removed value-carrying `onChange`, and 50 of 67 ended in
 * `[key: string]: unknown`, which turns off excess-property checking entirely. The site
 * compiled clean against props that no longer existed while every other guard stayed green.
 *
 * A **built `.d.ts` has no JSX bodies to check**, so re-exporting from the built `dist` bundles
 * gives the site the real, complete, generated types with none of the JSX problem — and
 * nothing left to keep in sync. Each shim is one re-export line. Drift is now structurally
 * impossible: `pnpm regen` rewrites these and CI's drift job fails if the result differs.
 *
 * Requires a prior build — it reads `dist`. That ordering already holds: CI builds before
 * type-checking, and so does `pnpm ready`.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildSnapshot } from '../api-surface/extract.ts'

const ROOT = fileURLToPath(new URL('../..', import.meta.url))
const SHIM_DIR = join(ROOT, 'apps/site/src/shims')
const TSCONFIG = join(ROOT, 'apps/site/tsconfig.json')

/** Packages whose built declarations can back a shim, in resolution order. */
const SOURCES = [
  { pkg: '@cascivo/react', from: 'packages/react/dist/index' },
  { pkg: '@cascivo/charts', from: 'packages/charts/dist/index' },
  { pkg: '@cascivo/editor', from: 'packages/editor/dist/index' },
]

/**
 * Value/type classification comes from `api-surface`'s extractor rather than the `type`
 * modifiers in the dist's own export statement: the bundler emits those lists with no
 * modifiers at all, so trusting them would re-export every prop interface as a value.
 * One parser, two consumers.
 */
const snapshot = buildSnapshot(ROOT)

const catalog = SOURCES.map((s) => {
  const entry = snapshot[s.pkg]?.['.']
  return {
    ...s,
    values: new Set(entry?.values ?? []),
    types: new Set(entry?.types ?? []),
  }
}).filter((s) => s.values.size > 0 || s.types.size > 0)

if (catalog.length !== SOURCES.length) {
  // Skip rather than fail: `pnpm regen` also runs in CI's drift job, which deliberately does
  // not build. Enforcement lives in `pnpm shims:check`, which runs after the build in CI and
  // in `ready` — so a stale shim still fails, just in the job that has `dist` to compare to.
  console.log('shims: skipped — built declarations absent (run `pnpm build` to regenerate)')
  process.exit(0)
}

/** Every name a shim currently exports, so the regenerated file serves the same specifier. */
function currentExports(source: string): string[] {
  const names = new Set<string>()
  for (const m of source.matchAll(/export declare (?:function|const) (\w+)/g)) names.add(m[1]!)
  for (const m of source.matchAll(/export (?:interface|type) (\w+)\b/g)) names.add(m[1]!)
  for (const m of source.matchAll(/(?:^|\n)export \{([^}]*)\}/g)) {
    for (const raw of m[1]!.split(',')) {
      const name = raw
        .replace(/^\s*type\s+/, '')
        .split(/\s+as\s+/)
        .pop()
        ?.trim()
      if (name) names.add(name)
    }
  }
  return [...names].sort()
}

const shimFiles = readdirSync(SHIM_DIR).filter((f) => f.endsWith('.d.ts'))
const unresolved: string[] = []
let written = 0

for (const file of shimFiles) {
  const path = join(SHIM_DIR, file)
  const wanted = currentExports(readFileSync(path, 'utf8'))

  /** package `from` → the specifiers to re-export from it. */
  const groups = new Map<string, { values: string[]; types: string[] }>()
  for (const name of wanted) {
    const home = catalog.find((c) => c.values.has(name) || c.types.has(name))
    if (home === undefined) {
      unresolved.push(`${file}: ${name}`)
      continue
    }
    if (!groups.has(home.from)) groups.set(home.from, { values: [], types: [] })
    const bucket = groups.get(home.from)!
    ;(home.values.has(name) ? bucket.values : bucket.types).push(name)
  }
  if (groups.size === 0) continue

  const lines = [
    '// Generated by scripts/shims/generate.ts — do not edit. Run `pnpm regen`.',
    '//',
    '// The site is Preact and the components are React, so it cannot compile against their',
    '// sources; it re-exports the built declarations instead, which carry the real types and',
    '// have no JSX bodies to check. See the generator for the full rationale.',
    '',
  ]
  for (const [from, { values, types }] of [...groups].sort()) {
    const specifiers = [...values.sort(), ...types.sort().map((t) => `type ${t}`)].join(', ')
    const rel = relative(SHIM_DIR, join(ROOT, from)).replaceAll('\\', '/')
    lines.push(`export { ${specifiers} } from '${rel.startsWith('.') ? rel : `./${rel}`}'`)
  }
  writeFileSync(path, `${lines.join('\n')}\n`)
  written += 1
}

if (!existsSync(TSCONFIG)) {
  console.error(`shims: ${TSCONFIG} missing`)
  process.exit(2)
}

if (unresolved.length > 0) {
  console.log(`shims: ${unresolved.length} name(s) not exported by any built package (dropped):`)
  for (const u of unresolved) console.log(`  ${u}`)
}
console.log(`shims: wrote ${written} shim(s) from built declarations`)
