export { assertSendable, CLIP_BUDGETS, renderEmail } from './render.tsx'
export type { ClipRisk, ClipTier, RenderOptions, RenderResult, RenderStats } from './render.tsx'
export { extractPreheader, toPlainText } from './plaintext.ts'
export type { PlainTextOptions } from './plaintext.ts'
export { buildMessage, quotedPrintable } from './message.ts'
export type { BuildMessageOptions, EmailMessage } from './message.ts'
export { minify } from './minify.ts'
export { analyze, formatAnalysis } from './analyze.ts'
export type { Analysis, TagCost } from './analyze.ts'
