// AUTO-GENERATED by scripts/style-contract/generate.ts — do not edit by hand.
// Run `pnpm style-contract:generate` (or `pnpm regen`) to refresh.

import type { CascivoToken } from './tokens.js'

/**
 * Every per-component token — the knobs the override ladder's first rung tells you to set
 * (`--cascivo-button-radius`, `--cascivo-dialog-body-gap`). Separate from
 * {@link CascivoToken}, which covers only the primitive and semantic layers.
 */
export type CascivoComponentToken =
  | '--cascivo-aspect-ratio'
  | '--cascivo-button-destructive-bg'
  | '--cascivo-button-destructive-bg-hover'
  | '--cascivo-button-ghost-bg'
  | '--cascivo-button-ghost-bg-hover'
  | '--cascivo-button-primary-bg'
  | '--cascivo-button-primary-bg-active'
  | '--cascivo-button-primary-bg-hover'
  | '--cascivo-button-radius'
  | '--cascivo-button-secondary-bg'
  | '--cascivo-button-secondary-bg-hover'
  | '--cascivo-calendar-bg'
  | '--cascivo-calendar-cell-size'
  | '--cascivo-calendar-day-selected-bg'
  | '--cascivo-calendar-day-selected-fg'
  | '--cascivo-calendar-day-today-color'
  | '--cascivo-calendar-radius'
  | '--cascivo-calendar-range-bg'
  | '--cascivo-chart-anim-dur'
  | '--cascivo-chart-anim-ease'
  | '--cascivo-chart-anim-props'
  | '--cascivo-color-focus-ring'
  | '--cascivo-color-picker-alpha-to'
  | '--cascivo-color-picker-area-size'
  | '--cascivo-color-scrim'
  | '--cascivo-color-surface-overlay'
  | '--cascivo-context-x'
  | '--cascivo-context-y'
  | '--cascivo-control-height-lg'
  | '--cascivo-control-height-md'
  | '--cascivo-control-height-sm'
  | '--cascivo-data-table-cell-gap'
  | '--cascivo-data-table-height'
  | '--cascivo-data-table-max-height'
  | '--cascivo-date-picker-day-today-color'
  | '--cascivo-dialog-body-gap'
  | '--cascivo-dropdown-anchor'
  | '--cascivo-editor-bracket'
  | '--cascivo-editor-caret-line'
  | '--cascivo-editor-gutter-active'
  | '--cascivo-editor-match'
  | '--cascivo-editor-match-current'
  | '--cascivo-editor-tab-size'
  | '--cascivo-flash-tint'
  | '--cascivo-focus-ring'
  | '--cascivo-header-bg'
  | '--cascivo-kpi-padding'
  | '--cascivo-link-color'
  | '--cascivo-logo-size'
  | '--cascivo-popover-anchor'
  | '--cascivo-progress-color'
  | '--cascivo-progress-value'
  | '--cascivo-radial-color'
  | '--cascivo-radial-progress'
  | '--cascivo-radial-size'
  | '--cascivo-radial-thickness'
  | '--cascivo-radius-badge'
  | '--cascivo-radius-button'
  | '--cascivo-radius-card'
  | '--cascivo-radius-control'
  | '--cascivo-radius-input'
  | '--cascivo-radius-modal'
  | '--cascivo-radius-overlay'
  | '--cascivo-radius-pill'
  | '--cascivo-resizable-ratio'
  | '--cascivo-ring-color'
  | '--cascivo-ring-offset'
  | '--cascivo-ring-width'
  | '--cascivo-scroll-area-height'
  | '--cascivo-scroll-area-width'
  | '--cascivo-search-width'
  | '--cascivo-shadow-overlay'
  | '--cascivo-shell-aside-inline-size'
  | '--cascivo-shell-header-block-size'
  | '--cascivo-shell-panel-inline-size'
  | '--cascivo-sidenav-bg'
  | '--cascivo-sidenav-inline-size'
  | '--cascivo-sidenav-rail-inline-size'
  | '--cascivo-skeleton-height'
  | '--cascivo-skeleton-width'
  | '--cascivo-stack-index'
  | '--cascivo-stack-offset'
  | '--cascivo-table-zebra-bg'
  | '--cascivo-target-min'
  | '--cascivo-textarea-max-block-size'
  | '--cascivo-tooltip-anchor'
  | '--cascivo-tree-indent'
  | '--cascivo-tree-level'
  | '--cascivo-z-dock'
  | '--cascivo-z-modal'
  | '--cascivo-z-overlay'

/** Any `--cascivo-*` custom property cascivo ships, at any layer. */
export type CascivoAnyToken = CascivoToken | CascivoComponentToken

/**
 * An inline style object whose custom properties are checked against the shipped token set.
 *
 * React's `CSSProperties` has no index signature for `--*` keys, so a custom property in a
 * `style` prop is unchecked by construction — every adopter writes the cast, and a typo in
 * the cast resolves to nothing at runtime with no diagnostic anywhere. Use `satisfies` to
 * get the name checked before the cast erases it:
 *
 * ```tsx
 * import type { CSSProperties } from 'react'
 * import type { CascivoTokenStyle } from '@cascivo/tokens/style-contract'
 *
 * const brand = {
 *   '--cascivo-button-bg': 'var(--cascivo-color-accent)',
 * } satisfies CascivoTokenStyle
 *
 * <Button style={brand as CSSProperties}>Save</Button>
 * ```
 *
 * A misspelled token is a compile error on the `satisfies` line, which is the whole point —
 * the cast is still yours, but it can no longer launder a name that does not exist.
 */
export type CascivoTokenStyle = {
  [K in CascivoAnyToken]?: string | number
}

/**
 * Every `data-cascivo-*` styling hook — the stable, semver'd selectors for reaching a
 * component's internals. See `docs/STYLING-INTERNALS.md`.
 *
 * CSS Modules hash internal class names, so a hook that does not exist is a rule that
 * matches nothing and says nothing. Typing the set turns that into an error at the one
 * place a type can reach it — tooling, tests, and any `querySelector` you write.
 */
export type CascivoStyleHook =
  | 'data-cascivo-appshell-main'
  | 'data-cascivo-appshell-nav'
  | 'data-cascivo-card'
  | 'data-cascivo-drawer-body'
  | 'data-cascivo-logo'
  | 'data-cascivo-modal-body'
  | 'data-cascivo-modal-footer'
  | 'data-cascivo-sheet-body'
