// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ActivityMonitor = createIcon(
  'ActivityMonitor',
  <>
    <rect x="2" y="3" width="20" height="14" rx="2" />
    <path d="M8 21h8M12 17v4M15.698 10h-1.479l-1.11 3.328-2.218-6.656L9.781 10H8.302" />
  </>,
)
