// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Airplay = createIcon(
  'Airplay',
  <path d="M5.7,15.6H4.8A1.8,1.8,0,0,1,3,13.8v-9A1.8,1.8,0,0,1,4.8,3H19.2A1.8,1.8,0,0,1,21,4.8v9a1.8,1.8,0,0,1-1.8,1.8h-.9m-6.3-1L17.5,21H6.5Z" />,
)
