// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const AlertOctagon = createIcon(
  'AlertOctagon',
  <path d="M8.274,3h7.452L21,8.274v7.452L15.726,21H8.274L3,15.726V8.274ZM12,7.65v5.2m0,3.39v.01" />,
)
