// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const AlignLeft = createIcon(
  'AlignLeft',
  <path d="M3,3H21M3,8.75H13.662M3,21H13.662M3,14.875H21" />,
)
