// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const AlignJustify = createIcon(
  'AlignJustify',
  <path d="M3,3H21M3,8.75H21M3,21H21M3,14.875H21" />,
)
