// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const AlignRight = createIcon('AlignRight', <path d="M3,3H21M10.338,8.75H21M10.338,21H21M3,14.875H21" />)
