// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const AlignCenter = createIcon('AlignCenter', <path d="M3,3H21M6.669,8.75H17.331M6.669,21H17.331M3,14.875H21" />)
