// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Aperture = createIcon('Aperture', <path d="M21,12a9,9,0,1,1-9-9A9,9,0,0,1,21,12ZM7.017,11.986,12,3.355M4.541,7.7l4.953,8.578M13.7,16.3H4.907m12.076-4.289-4.9,8.482M19.459,16.3,14.506,7.725M9.8,7.7h9.289" />)
