// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowDownRight = createIcon(
  'ArrowDownRight',
  <path d="M18.364,18.364,5.636,5.636M9.274,18.364h9.09V9.274" />,
)
