// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowRight3 = createIcon(
  'ArrowRight3',
  <path d="M12.9333 16.6667L18 12M18 12L6 12M18 12L12.9333 7.33335" />,
)
