// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowUp3 = createIcon(
  'ArrowUp3',
  <path d="M16.6667 11.0667L12 6M12 6L12 18M12 6L7.33335 11.0667" />,
)
