// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowDownLeft = createIcon('ArrowDownLeft', <path d="M18.364,5.636,5.636,18.364m0-9.09v9.09h9.09" />)
