// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowLeftCircle = createIcon(
  'ArrowLeftCircle',
  <path d="M15.858,12H8.142l1.9,1.75,1.9,1.75m0-7-1.9,1.75L8.142,12M12,21a9,9,0,1,1,9-9A9,9,0,0,1,12,21Z" />,
)
