// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowUp2 = createIcon('ArrowUp2', <path d="M17.4445 10.9111L12 5M12 5L12 19M12 5L6.55557 10.9111" />)
