// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowDown3 = createIcon(
  'ArrowDown3',
  <path d="M7.33331 12.9333L12 18M12 18L12 6M12 18L16.6666 12.9333" />,
)
