// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowRight2 = createIcon('ArrowRight2', <path d="M13.0889 17.4445L19 12M19 12L5 12M19 12L13.0889 6.55557" />)
