// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowDownCircle = createIcon(
  'ArrowDownCircle',
  <path d="M12,8.142v7.716l1.75-1.9,1.75-1.9m-7,0,1.75,1.9,1.75,1.9M21,12a9,9,0,1,1-9-9A9,9,0,0,1,21,12Z" />,
)
