// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowRightCircle = createIcon(
  'ArrowRightCircle',
  <path d="M8.142,12h7.716l-1.9-1.75-1.9-1.75m0,7,1.9-1.75,1.9-1.75M12,3a9,9,0,1,1-9,9A9,9,0,0,1,12,3Z" />,
)
