// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowUpLeft = createIcon('ArrowUpLeft', <path d="M5.636,5.636,18.364,18.364M14.726,5.636H5.636v9.09" />)
