// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowLeft2 = createIcon('ArrowLeft2', <path d="M10.9111 6.55554L5 12M5 12H19M5 12L10.9111 17.4444" />)
