// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowDown2 = createIcon('ArrowDown2', <path d="M6.55554 13.0889L12 19M12 19L12 5M12 19L17.4444 13.0889" />)
