// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowLeft3 = createIcon(
  'ArrowLeft3',
  <path d="M11.0667 7.33331L6 12M6 12H18M6 12L11.0667 16.6666" />,
)
