// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowUpCircle = createIcon('ArrowUpCircle', <path d="M12,15.858V8.142l-1.75,1.9-1.75,1.9m7,0-1.75-1.9L12,8.142M3,12a9,9,0,1,1,9,9A9,9,0,0,1,3,12Z" />)
