// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ArrowUpRight = createIcon(
  'ArrowUpRight',
  <path d="M5.636,18.364,18.364,5.636m0,9.09V5.636H9.274" />,
)
