// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const AtSymbol = createIcon(
  'AtSymbol',
  <path d="M20.027,16.075m0,0M12,8.5A3.5,3.5,0,1,0,15.5,12,3.5,3.5,0,0,0,12,8.5Zm3.5,0v4.455a2.716,2.716,0,0,0,3.084,2.529A2.9,2.9,0,0,0,20.933,12.9,5.911,5.911,0,0,0,21,12a9,9,0,1,0-3.935,7.44" />,
)
