// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Award = createIcon(
  'Award',
  <path d="M17.507,8.507a5.507,5.507,0,1,1-1.613-3.894A5.49,5.49,0,0,1,17.507,8.507ZM8.8,12.985l-.465,4.008L7.87,21l2.168-1.608,2.167-1.608,2.168,1.608L16.54,21l-.584-4.007-.585-4.008" />,
)
