// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const BandAid = createIcon('BandAid', <path d="M4.505,19.586h0a4.883,4.883,0,0,1,0-6.828l8.213-8.344a4.7,4.7,0,0,1,6.721,0h0a4.883,4.883,0,0,1,0,6.828l-8.213,8.344A4.7,4.7,0,0,1,4.505,19.586Zm13.309-6.913L11.062,6.1m1.792,11.836L6.072,11.166m6.941,2.008.005-.095m-2.27-2.158.006-.095" />)
