// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Bank = createIcon(
  'Bank',
  <path d="M3,21H21m-9.06-7.853v4.836m-6.3-4.836v4.836m12.718-4.836v4.836M12,3,3,10.13H21Zm0,4.031v-.05h0" />,
)
