// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const BarChart2 = createIcon('BarChart2', <path d="M15,21V9.1h6V21H3V15.4H9V21m0,0V3h6V21" />)
