// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const BatteryCharging = createIcon('BatteryCharging', <path d="M9.759,17.593H5a2,2,0,0,1-2-2V8.407a2,2,0,0,1,2-2h.746m5.017,0H15.3a2,2,0,0,1,2,2v7.186a2,2,0,0,1-2,2M10.763,6.407m-5.973,0M21,10.506v2.988M9.3,19.5l3.8-7.35H7.5L11.849,4.5" />)
