// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Battery = createIcon('Battery', <path d="M15.3,17.593H5a2,2,0,0,1-2-2V8.407a2,2,0,0,1,2-2H15.3a2,2,0,0,1,2,2v7.186A2,2,0,0,1,15.3,17.593ZM21,10.506v2.988" />)
