// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Beaker = createIcon('Beaker', <path d="M15.181,3V8.822a2,2,0,0,0,.569,1.4l4.186,4.286A3.738,3.738,0,0,1,21,17.117v.145A3.739,3.739,0,0,1,17.262,21H6.738A3.739,3.739,0,0,1,3,17.262H3a3.737,3.737,0,0,1,1.041-2.588l4.221-4.4A2,2,0,0,0,8.819,8.89V3M6.378,3H17.622M12.978,5.905h2.2m-2.2,2.905h2.2" />)
