// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const BellOff = createIcon('BellOff', <path d="M17.4,17.9H5.3m1.3,0V10.4a5.364,5.364,0,0,1,.8-2.8m3.4-2.5a3.355,3.355,0,0,1,.6-.088C11.6,5,11.8,5,12,5a5.378,5.378,0,0,1,5.4,5.4v1.4M9.912,18.6a2.508,2.508,0,0,0-.012.3,2.1,2.1,0,1,0,4.2,0,2.627,2.627,0,0,0-.013-.313M4.3,4.5,12,12.15l7.7,7.65M12,5V3" />)
