// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Bold = createIcon('Bold', <path d="M8.561,3V21m.674-9h3.086a4.5,4.5,0,0,0,4.5-4.5h0a4.5,4.5,0,0,0-4.5-4.5H5.345m0,18h8.81a4.5,4.5,0,0,0,4.5-4.5h0a4.5,4.5,0,0,0-4.5-4.5H8.561" />)
