// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Bookmark = createIcon('Bookmark', <path d="M19,3V21l-7-5L5,21V3M3,3H21" />)
