// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Book = createIcon(
  'Book',
  <path d="M18.259,21H7.059a2.318,2.318,0,0,1-2.318-2.318V5.318A2.318,2.318,0,0,1,7.059,3h11.2a1,1,0,0,1,1,1V20A1,1,0,0,1,18.259,21Zm1-4.438H6.96a2.22,2.22,0,0,0-2.219,2.219h0M8.936,3V8.659" />,
)
