// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Bowl = createIcon('Bowl', <path d="M21,9.986C21,16.005,16.954,21,12,21s-9-5-9-11.014m10.016,3.306L18.307,3M12.318,6.664a2.81,2.81,0,0,0-.318,0c-4.962,0-9,1.486-9,3.322s4.038,3.327,9,3.327,9-1.491,9-3.327c0-1.339-1.638-2.517-4.719-3.044" />)
