// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Bread = createIcon(
  'Bread',
  <path d="M20.4,10.25V21H3.634V10.31A3.528,3.528,0,0,1,3,8.347C3,5.394,7.029,3,12,3s9,2.394,9,5.347A3.5,3.5,0,0,1,20.4,10.25Zm-6.14,3.694,0-.1m2.106,2.094-.006.1m-3.2.63,0-.1" />,
)
