// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Briefcase = createIcon('Briefcase', <path d="M21,19a2.006,2.006,0,0,1-2,2H5a2.006,2.006,0,0,1-2-2V10.207a2.006,2.006,0,0,1,2-2H19a2.006,2.006,0,0,1,2,2ZM15.428,8.207V5a2.006,2.006,0,0,0-2-2H10.572a2.006,2.006,0,0,0-2,2V8.207M3,13.62H21" />)
