// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Calculator = createIcon('Calculator', <path d="M19.648,21H4.352V3h15.3ZM7.689,13.676v-.045h0M12,13.676v-.045h0m4.327.045v-.045h0M7.689,17.442V17.4h0M12,17.442V17.4h0m4.327.045V17.4h0M16.319,6.419H7.681V9.748" />)
