// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CheckSquare = createIcon(
  'CheckSquare',
  <path d="M8.5,13.1l1.05.95L10.6,15l2.45-3L15.5,9M19,21H5a2.006,2.006,0,0,1-2-2V5A2.008,2.008,0,0,1,5,3H19a2.006,2.006,0,0,1,2,2V19a2,2,0,0,1-2,2Z" />,
)
