// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CheckFile = createIcon(
  'CheckFile',
  <>
    <path d="M20 8.5l-7.999 9L9 14.5" />
    <path d="M20 4.5V4a2 2 0 00-2-2h-8L4 8v12a2 2 0 002 2h12a2 2 0 002-2v-4" />
    <path d="M4 8h6V2" />
  </>,
)
