// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CheckList = createIcon(
  'CheckList',
  <>
    <path d="M12.768 4.019L6.973 9.82 5.235 8.082" />
    <path d="M12.656 9.793a5.8 5.8 0 11-4.54-6.823l.04.008M16.268 8.143h6.554M14.58 14.143h8.242M4.822 20.143h18" />
  </>,
)
