// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ChevronLeft2 = createIcon(
  'ChevronLeft2',
  <path d="M14.2892 16.5096L9.9797 12.0515L14.2892 7.59337" />,
)
