// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ChevronRight2 = createIcon('ChevronRight2', <path d="M9.87277 7.49036L14.1823 11.9485L9.87277 16.4066" />)
