// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ChevronDown2 = createIcon(
  'ChevronDown2',
  <path d="M16.5096 9.87277L12.0515 14.1823L7.5934 9.87277" />,
)
