// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ChevronUp2 = createIcon('ChevronUp2', <path d="M7.49039 14.1272L11.9485 9.81771L16.4066 14.1272" />)
