// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Chroma = createIcon('Chroma', <path d="M12,7.8A6.6,6.6,0,1,1,7.333,9.733,6.58,6.58,0,0,1,12,7.8ZM5.4,3H18.6" />)
