// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Circle = createIcon('Circle', <path d="M21,12a9,9,0,1,1-9-9A9,9,0,0,1,21,12Z" />)
