// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ClearList = createIcon(
  'ClearList',
  <path d="M3 12h18M3 6h10.867M3 18h18M21 4l-4 4M17 4l4 4" />,
)
