// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ClockForward = createIcon('ClockForward', <path d="M17.128,8.372,21,8.4V4.288M21,12.7A9.038,9.038,0,0,1,12,21,9.011,9.011,0,1,1,19.5,7M12,9.183v4h4.2" />)
