// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ClockRewind = createIcon('ClockRewind', <path d="M2.985,4.288V8.4l3.872-.028M4.485,7a8.989,8.989,0,1,1-1.5,5.7M12,9.183v4h4.2" />)
