// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CloudDrizzle = createIcon('CloudDrizzle', <path d="M20.2,14.925a3.677,3.677,0,0,0-1.308-5.612A5.551,5.551,0,1,0,7.88,7.919a4.158,4.158,0,0,0-.645-.065A4.234,4.234,0,0,0,4.141,14.98M8.2,18v1.614m0-6.966v2m3.788,4.738V21m0-6.966v2M15.8,18v1.614m0-6.966v2" />)
