// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Code = createIcon('Code', <path d="M6.5,8.6,4.75,10.35,3,12.1l1.65,1.65L6.3,15.4M17.5,8.6l1.75,1.75L21,12.1l-1.65,1.65L17.7,15.4M14.2,5.8,12,12,9.8,18.2" />)
