// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Codepen = createIcon('Codepen', <path d="M12,21,3,15.133V8.884L12,3V3l9,5.885v6.249L12,21ZM3.041,8.845,12,15.151v0l8.959-6.306m-.115,6.1L12,8.718l0,0L3.156,14.945M12,3V8.714m0,6.437V21" />)
