// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Coffee = createIcon('Coffee', <path d="M16.718,9.778h.858a3.458,3.458,0,0,1,0,6.916h-.858M2.993,9.778H16.718v7.78a3.444,3.444,0,0,1-3.431,3.458H6.424a3.444,3.444,0,0,1-3.431-3.458ZM6.236,2.984V4.691M9.855,2.984V6.471m3.62-1.954v1.2" />)
