// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Command = createIcon('Command', <path d="M12,9.023H6a3,3,0,0,1-3-3V6A3,3,0,0,1,6,3h.023a3,3,0,0,1,3,3v8M12,9.023h6a3,3,0,0,0,3-3V6a3,3,0,0,0-3-3h-.023a3,3,0,0,0-3,3v8M12,14.977H6a3,3,0,0,0-3,3V18a3,3,0,0,0,3,3h.023a3,3,0,0,0,3-3V10m5.954,0v8a3,3,0,0,0,3,3H18a3,3,0,0,0,3-3v-.023a3,3,0,0,0-3-3H12" />)
