// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Compass = createIcon('Compass', <path d="M8.142,16.005l1.928-5.636L15.858,8l-2.252,5.91ZM12,3a9,9,0,1,0,9,9A9,9,0,0,0,12,3Z" />)
