// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ControlPolicy = createIcon(
  'ControlPolicy',
  <>
    <path d="M13.25 22H18a2 2 0 002-2V8l-6-6H6a2 2 0 00-2 2v1.572" />
    <path d="M14 2v6h6M3.25 23v-5.25M3.25 14.75V9.5M9.25 23v-6.75M9.25 13.25V9.5M1 17.75h4.5M7 13.25h4.5" />
  </>,
)
