// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Container = createIcon('Container', <path d="M5 8.5h14v7H5zM9.667 8.5v7M14.333 8.5v7" />)
