// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerDownLeft2 = createIcon('CornerDownLeft2', <path d="M19 5V10.5261C19 11.5575 18.5903 12.5467 17.861 13.276C17.1317 14.0053 16.1425 14.415 15.1111 14.415H5M5 14.415L9.58889 19M5 14.415L9.58889 9.83" />)
