// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerUpRight2 = createIcon(
  'CornerUpRight2',
  <path d="M5 5L5 10.5261C5 11.5575 5.40972 12.5467 6.13903 13.276C6.86834 14.0053 7.85749 14.415 8.88889 14.415L19 14.415M19 14.415L14.4111 19M19 14.415L14.4111 9.83" />,
)
