// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerLeftDown2 = createIcon('CornerLeftDown2', <path d="M19 5L13.4739 5C12.4425 5 11.4533 5.40972 10.724 6.13903C9.99472 6.86834 9.585 7.85749 9.585 8.88889L9.585 19M9.585 19L5 14.4111M9.585 19L14.17 14.4111" />)
