// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerRightUp = createIcon(
  'CornerRightUp',
  <path d="M15.066,3V16a5,5,0,0,1-5,5h-7.1M15.066,3m0,0,5.973,5.816M15.066,3,9.092,8.974" />,
)
