// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerLeftUp2 = createIcon(
  'CornerLeftUp2',
  <path d="M19 19L13.4739 19C12.4425 19 11.4533 18.5903 10.724 17.861C9.99472 17.1317 9.585 16.1425 9.585 15.1111L9.585 5M9.585 5L5 9.58889M9.585 5L14.17 9.58889" />,
)
