// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerLeftDown = createIcon('CornerLeftDown', <path d="M8.9,21V8a5,5,0,0,1,5-5H21M8.9,21m0,0L3,15.105M8.9,21l5.9-5.895" />)
