// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerDownLeft = createIcon('CornerDownLeft', <path d="M21,3v7.105a5,5,0,0,1-5,5H3m0,0M8.9,21,3,15.105M8.9,9.21,3,15.105" />)
