// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerUpRight = createIcon(
  'CornerUpRight',
  <path d="M21,15.105H8a5,5,0,0,1-5-5V3M21,15.105m0,0L15.105,21M21,15.105,15.105,9.21" />,
)
