// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerRightDown2 = createIcon(
  'CornerRightDown2',
  <path d="M5 5L10.5261 5C11.5575 5 12.5467 5.40972 13.276 6.13903C14.0053 6.86834 14.415 7.85749 14.415 8.88889L14.415 19M14.415 19L19 14.4111M14.415 19L9.83 14.4111" />,
)
