// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerLeftUp = createIcon(
  'CornerLeftUp',
  <path d="M13.7,8.8,11,5.9,8.3,3V15.3A5.7,5.7,0,0,0,14,21h7M8.3,3,5.65,5.9,3,8.8" />,
)
