// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerRightUp2 = createIcon(
  'CornerRightUp2',
  <path d="M5 19L10.5261 19C11.5575 19 12.5467 18.5903 13.276 17.861C14.0053 17.1317 14.415 16.1425 14.415 15.1111L14.415 5M14.415 5L19 9.58889M14.415 5L9.83 9.58889" />,
)
