// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CornerRightDown = createIcon(
  'CornerRightDown',
  <path d="M3,3h7.105a5,5,0,0,1,5,5V21m0,0M21,15.105,15.105,21M9.21,15.105l5.9,5.9" />,
)
