// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Crop = createIcon('Crop', <path d="M21,16.926h-9.85a4,4,0,0,1-4-4V2.969m9.692,18.062V11.074a4,4,0,0,0-4-4H3" />)
