// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Crosshair = createIcon(
  'Crosshair',
  <path d="M21,12a9,9,0,1,1-9-9A9,9,0,0,1,21,12ZM12,7.309V3m0,18V16.691M7.309,12.167H3m18,0H16.691" />,
)
