// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const CryptoKey = createIcon(
  'CryptoKey',
  <>
    <circle cx="16.551" cy="7.449" r="2" />
    <path d="M19.552 14.74a7.451 7.451 0 10-10.939-3.547L1 18.789V23h4.211l1.759-1.82V18.8h.011l.99-1.025h2.432l2.371-2.4a6.856 6.856 0 00.656.227M16.551 9.449v10.744M16.551 20.193H19" />
    <circle cx="21" cy="20.193" r="2" />
    <path d="M8.162 7.449H5" />
    <circle cx="3" cy="7.449" r="2" />
  </>,
)
