// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Delete = createIcon(
  'Delete',
  <path d="M14,12l2.71,2.71m-5.42-5.42L14,12m2.71-2.71L14,12l-2.71,2.71M18,4.978H9.079L3,12.167l6.079,6.855H18a3,3,0,0,0,3-3V7.978A3,3,0,0,0,18,4.978Z" />,
)
