// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Disc = createIcon('Disc', <path d="M21,12a9,9,0,1,1-9-9A9,9,0,0,1,21,12ZM12,9.239A2.761,2.761,0,1,0,14.761,12,2.761,2.761,0,0,0,12,9.239Z" />)
