// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const DomainRecord = createIcon(
  'DomainRecord',
  <>
    <path d="M12 22a10 10 0 119.55-12.976M2 12h12.36" />
    <path d="M12 22a15.3 15.3 0 01-4-10 15.3 15.3 0 014-10 15.306 15.306 0 013.572 6.712M18.989 12.112L23 23l-4.011-2.292L14.977 23l4.012-10.888z" />
  </>,
)
