// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const DownloadCloud = createIcon(
  'DownloadCloud',
  <path d="M20.2,14.925a3.677,3.677,0,0,0-1.308-5.612A5.551,5.551,0,1,0,7.88,7.919a4.158,4.158,0,0,0-.645-.065A4.234,4.234,0,0,0,4.141,14.98M12,11.35V21l1.75-1.9,1.75-1.9m-7,0,1.75,1.9L12,21" />,
)
