// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Droplet = createIcon('Droplet', <path d="M17.116,10.609h0L12,3,6.742,10.8q-.1.135-.186.276l-.027.04h0a6.459,6.459,0,1,0,10.585-.505Z" />)
