// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Facebook = createIcon(
  'Facebook',
  <path d="M16.95,3h-2.7a4.5,4.5,0,0,0-4.5,4.5v2.7H7.05v3.6h2.7V21h3.6V13.8h2.7l.9-3.6h-3.6V7.5a.9.9,0,0,1,.9-.9h2.7Z" />,
)
