// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const FastForward = createIcon('FastForward', <path d="M11,12.014,2.986,18.138V5.837Zm2-6.152v12.3l8.015-6.123Z" />)
