// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const FemaleSymbol = createIcon(
  'FemaleSymbol',
  <path d="M17.5,8.5A5.5,5.5,0,1,1,12,3,5.5,5.5,0,0,1,17.5,8.5ZM12,14l0,7M9.06,18.057l5.88-.019" />,
)
