// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const FileText = createIcon(
  'FileText',
  <path d="M13.15,2.75h-7.3c-.52-.03-.97.37-1,.89,0,.04,0,.08,0,.11v16c-.03.52.37.97.89,1,.04,0,.08,0,.11,0h11.8c.52.03.97-.37,1-.89,0-.04,0-.08,0-.11v-11.5h-5.5V2.75ZM13.15,2.75l2.75,2.75,2.75,2.75M8.75,12.55h6M8.75,16.35h6M9.89,8.55h-1.14" />,
)
