// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Floss = createIcon(
  'Floss',
  <path d="M14.5,21H3V11.2H14.5ZM3,15.3H6.6a2.112,2.112,0,0,0,2.1,2.1,2.051,2.051,0,0,0,2.1-2.1h3.5m6.7-9v.2a2.9,2.9,0,0,1-2.9,2.9H18a2.9,2.9,0,0,1-2.9-2.9V5.9A2.9,2.9,0,0,0,12.2,3h0A3.372,3.372,0,0,0,8.8,6.4h0v4.8" />,
)
