// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const FontSize = createIcon(
  'FontSize',
  <path d="M18.215,3V21M15.426,5.787,18.213,3,21,5.787m0,12.426L18.213,21l-2.787-2.787M7.468,6.032V17.968M3,7.224V6.032h8.936V7.224M5.284,17.968H9.652" />,
)
