// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Fork = createIcon('Fork', <path d="M18 2v6a4.012 4.012 0 01-4 4h-4a4.012 4.012 0 01-4-4V2M12 2v20" />)
