// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Function = createIcon(
  'Function',
  <path d="M8 4a3 3 0 00-3 3v2a3 3 0 01-3 3 3 3 0 013 3v2a3 3 0 003 3M16 20a3 3 0 003-3v-2a3 3 0 013-3 3 3 0 01-3-3V7a3 3 0 00-3-3" />,
)
