// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Gauge2 = createIcon(
  'Gauge2',
  <>
    <path d="M5.63,19.22a9,9,0,1,1,12.737,0" />
    <path d="M12,7.349a5.5,5.5,0,0,1,.967.086" />
    <path d="M6.5,12.849a5.506,5.506,0,0,1,5.5-5.5" />
    <circle cx="12" cy="12.849" r="2" />
    <line x1="13.414" y1="11.435" x2="15.802" y2="9.047" />
  </>,
)
