// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Gift = createIcon('Gift', <path d="M19.2,12v9H4.8V12M3,7.5H21V12H3ZM12,21V7.5m0,0H7.95a2.25,2.25,0,1,1,0-4.5C11.1,3,12,7.5,12,7.5Zm0,0h4.05a2.25,2.25,0,0,0,0-4.5C12.9,3,12,7.5,12,7.5Z" />)
