// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const GlassStraw = createIcon('GlassStraw', <path d="M18.536,14.4a15.41,15.41,0,0,1-6.9.446,20.031,20.031,0,0,0-3.772-.525,18.5,18.5,0,0,0-2.483.079M6.748,7.354,4.759,7.348,5.925,21H17.856L19.241,7.391,6.748,7.354m8.4-.006.035,7.646m-.035-7.646L19.822,3" />)
