// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Hash = createIcon(
  'Hash',
  <path d="M10.45,2.75l-2,9-2,9m10.6-18-2,9-2,9m7.7-12.1h-17m16,6.7h-17" />,
)
