// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Headphones = createIcon('Headphones', <path d="M3,18V12a9,9,0,0,1,18,0v6m0,1a2,2,0,0,1-2,2h0a3,3,0,0,1-3-3V17a3,3,0,0,1,3-3h2ZM3,19a2,2,0,0,0,2,2H5a3,3,0,0,0,3-3V17a3,3,0,0,0-3-3H3Z" />)
