// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const HeartCheck = createIcon(
  'HeartCheck',
  <>
    <path d="m16.99,4.34c-1.44-.22-2.97.22-4.08,1.33l-.92.91-.91-.91c-1.89-1.81-4.89-1.73-6.7.16-1.74,1.83-1.74,4.71,0,6.54l.91.91,6.7,6.7,6.7-6.7.91-.91c.99-.99,1.45-2.31,1.38-3.61" />
    <path d="m9.64,10.86l2.36,2.14,8.98-8.24" />
  </>,
)
