// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Heatmap = createIcon('Heatmap', <path d="M3,21H21M3,16.8H16.2m4.8,0h-.9M3,12H8.6m3.1,0h4m3.1,0H21M3,7.2H4.4m3.7,0H9.6m4.1,0h1.9m3.8,0H21M3,3.1V3H3m7,.1V3h0m11,.1V3h0" />)
