// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Helix2 = createIcon(
  'Helix2',
  <path d="M7.5 3.5a8.492 8.492 0 001.4 5.3M16 3.5c0 2.6-1.6 5.5-3.8 7.7S7.1 15 7.1 20M14.3 14.7a9.654 9.654 0 011.7 5.8" />,
)
