// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Hexagon = createIcon('Hexagon', <path d="M20.1,15.6V8.4a1.8,1.8,0,0,0-.9-1.557l-6.3-3.6a1.8,1.8,0,0,0-1.8,0l-6.3,3.6A1.8,1.8,0,0,0,3.9,8.4v7.2a1.8,1.8,0,0,0,.9,1.557l6.3,3.6a1.8,1.8,0,0,0,1.8,0l6.3-3.6A1.8,1.8,0,0,0,20.1,15.6Z" />)
