// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Hook = createIcon(
  'Hook',
  <>
    <circle cx="12" cy="5.1" r="3" />
    <path d="M14.8 18c1-.6 1.5-2.2 1.5-2.2h0c.2.4.3.9.3 1.3 0 2-1.3 3.8-3.2 4.5-2.5.9-5.2-.3-6-2.8h0c-.2-.5-.3-1-.3-1.6 0-3.2 4.9-4.1 4.9-5.7V8.1" />
  </>,
)
