// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const HorizontalArrows = createIcon(
  'HorizontalArrows',
  <path d="M3.009,12H20.991m-17.977.006L5.8,14.787M3.005,12.006l2.78-2.793M20.982,12l-2.8-2.762M20.991,12l-2.76,2.812" />,
)
