// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const HorizontalArrows2 = createIcon('HorizontalArrows2', <path d="M16.941,6.981H3M6.982,3,3,6.982m3.982,3.981L3,6.982M6.982,17.019H21m-3.982-3.981L21,17.018M17.018,21,21,17.018" />)
