// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const HospitalSign = createIcon('HospitalSign', <path d="M20.921,12a8.961,8.961,0,1,1-8.96-9A8.98,8.98,0,0,1,20.921,12ZM9.372,11.984l5.178.032M9.278,7.989v8.359m5.365-8.359v8.359" />)
