// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Host = createIcon(
  'Host',
  <>
    <rect x="2" y="8" width="20" height="8" rx="2" />
    <path d="M6 12h0" />
  </>,
)
