// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const HostAgent = createIcon(
  'HostAgent',
  <>
    <path d="M10.348 16H4a2 2 0 01-2-2v-4a2 2 0 012-2h16a2 2 0 012 2v4a1.982 1.982 0 01-.109.652M6 12h0" />
    <path d="M23 18.652h-1.932L19.619 23l-2.899-8.695-1.449 4.347h-1.932" />
  </>,
)
