// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Instagram = createIcon('Instagram', <path d="M7.5,3h9A4.5,4.5,0,0,1,21,7.5v9A4.5,4.5,0,0,1,16.5,21h-9A4.5,4.5,0,0,1,3,16.5v-9A4.5,4.5,0,0,1,7.5,3Zm8.1,8.433A3.6,3.6,0,1,1,12.567,8.4,3.6,3.6,0,0,1,15.6,11.433ZM16.95,6.9v.15h.009" />)
