// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Italic = createIcon(
  'Italic',
  <path d="M14.818,3,9.182,21M5.818,21h6.729M11.453,3h6.729" />,
)
