// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Iv = createIcon('Iv', <path d="M12.005,15.14H3.324V3.935h8.681Zm-4.34,0v2.321A3.645,3.645,0,0,0,11.408,21h0a3.081,3.081,0,0,0,3.164-2.991v-.574a3.082,3.082,0,0,1,3.165-2.991h.1A3.081,3.081,0,0,1,21,17.435V21M9.435,7.561h2.57M7.665,3v.935M8.031,11.4H12" />)
