// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const KeyboardDown = createIcon('KeyboardDown', <path d="M7.5,5.47h0M7.5,8.47h0M10.5,5.47h0M10.5,8.47h0M13.5,5.47h0M13.5,8.47h0M16.5,5.47h0M16.5,8.47h0M14.97,11.63h-6M21,3.97l-1,9c0,1.1-.9,2-2,2H6c-1.1,0-2-.9-2-2L3,3.97M14.49,18.38l-2.49,2.29-2.49-2.29" />)
