// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Layout = createIcon(
  'Layout',
  <path d="M19,21H5a2.006,2.006,0,0,1-2-2V5A2.008,2.008,0,0,1,5,3H19a2.006,2.006,0,0,1,2,2V19a2,2,0,0,1-2,2ZM21,8.7H3m6.5,0V21" />,
)
