// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Leaf = createIcon(
  'Leaf',
  <path d="M12.031,3A8.952,8.952,0,1,0,21,11.956L21.01,3S12.04,3.013,12.031,3ZM3.015,20.988,16.755,7.247m-1.666,8.505H8.251V8.914m8.909,2.692H12.4V6.843" />,
)
