// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Library = createIcon('Library', <path d="M20.332 20L16.844 4M12 20V4M6 20V4" />)
