// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const LifeBuoy = createIcon(
  'LifeBuoy',
  <path d="M12,21a9,9,0,1,0-9-9A9,9,0,0,0,12,21Zm0-5.4A3.6,3.6,0,1,0,8.4,12,3.6,3.6,0,0,0,12,15.6ZM5.637,5.637,9.453,9.453m5.094,5.094,3.816,3.816m-3.816-8.91,3.816-3.816M14.547,9.453l3.177-3.177M5.637,18.363l3.816-3.816" />,
)
