// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const LineHeight = createIcon('LineHeight', <path d="M3,5.6h8.01M3,12h8.01M3,18.4h8.01M18.217,3V21M15.427,5.787,18.214,3,21,5.787m0,12.426L18.214,21l-2.787-2.787" />)
