// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Link2 = createIcon(
  'Link2',
  <path d="M14.456,7.907h2.456a4.093,4.093,0,0,1,0,8.186H14.456m-4.912,0H7.088a4.093,4.093,0,0,1,0-8.186H9.544M8.726,12h6.548" />,
)
