// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const List = createIcon('List', <path d="M9.6,5.6H21M9.6,12H21M9.6,18.4H21M4.5,4.1a1.5,1.5,0,1,1-1.061.439A1.5,1.5,0,0,1,4.5,4.1Zm0,6.4a1.5,1.5,0,1,1-1.061.439A1.5,1.5,0,0,1,4.5,10.5Zm0,6.4a1.5,1.5,0,1,1-1.061.439A1.5,1.5,0,0,1,4.5,16.9Z" />)
