// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Liver2 = createIcon('Liver2', <path d="M14.92,10.85c0,4.2-3.4,7.61-7.61,7.61l-4.31.02v-6.48c0-5.29,5.22-7.75,9.31-5.83,1.41.66,2.97.53,4.51.24,1.24-.24,3.41-.27,4.17-.2v1.67c0,3.07-2.32,5.91-6.56,5.65" />)
