// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Liver = createIcon(
  'Liver',
  <path d="M14.9,9.3c0,4.2-3.4,7.6-7.6,7.6H3s0-6.5,0-6.5c0-5.3,5.2-7.7,9.3-5.8,1.4.7,3,.5,4.5.2,1.2-.2,3.4-.3,4.2-.2v1.7c0,3.1-2.5,5.6-5.6,5.6M12.2,15.2v5.8M10.5,11.3h0c-1.6,1.2-2.9,2.8-2.9,8.9v.7M7.6,20.3s.3-5-2-7" />,
)
