// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Loader2 = createIcon(
  'Loader2',
  <path d="M5.7,5.7l1.05,1.05,1.05,1.05M6.1,12h-3.1M12,21v-3.1M12,3v3.1M5.88,18.09l.95-.95.95-.95M16.2,7.8l1.05-1.05,1.05-1.05M21,12h-3.1M12,17.9v3.1M12,6.1v-3.1M16.23,16.19l.95.95.95.95" />,
)
