// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Login = createIcon(
  'Login',
  <path d="M11.5,16.2l2.3-2.1L16.1,12H3m13.1,0L13.8,9.9,11.5,7.8M15.1,3H19a2.006,2.006,0,0,1,2,2V19a2,2,0,0,1-2,2H15.1" />,
)
