// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Mail = createIcon(
  'Mail',
  <path d="M3,5.75H21v12.5H3V5.75Zm0,0,3.9,3,3.9,3a2.107,2.107,0,0,0,2.4,0l3.9-3,3.9-3" />,
)
