// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const MailOpen = createIcon(
  'MailOpen',
  <>
    <path d="M21,21.438V8.937l-7.8,6a2.107,2.107,0,0,1-2.4,0l-3.9-3-3.9-3v12.5Z" />
    <path d="M3,8.937l7.8-6a2.108,2.108,0,0,1,2.4,0l7.8,6" />
  </>,
)
