// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const MaleSymbol = createIcon(
  'MaleSymbol',
  <path d="M16.972,14.014A6.986,6.986,0,1,1,9.986,7.028,6.986,6.986,0,0,1,16.972,14.014ZM20.966,3.007,14.879,9.019M16.83,3.014,20.959,3m0,0V7.143" />,
)
