// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Maximize2 = createIcon(
  'Maximize2',
  <path d="M21,3l-7,7M3,21l7-7M15,3h6V9M9,21H3V15" />,
)
