// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Maximize = createIcon(
  'Maximize',
  <path d="M3,8.3V3H8.3M3,15.7V21H8.3M21,8.3V3H15.7m0,18H21V15.7" />,
)
