// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const MedicalBriefcase = createIcon(
  'MedicalBriefcase',
  <path d="M8.166,5.5m3.843,6.684v5.287m2.4-2.561-4.807-.024M21,10.207a2.006,2.006,0,0,0-2-2H5a2.006,2.006,0,0,0-2,2V19a2.006,2.006,0,0,0,2,2H19a2.006,2.006,0,0,0,2-2Zm-12.428-2V5a2.006,2.006,0,0,1,2-2h2.856a2.006,2.006,0,0,1,2,2V8.207" />,
)
