// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const MessageCircle = createIcon('MessageCircle', <path d="M21,11.5a8.386,8.386,0,0,1-.9,3.8A8.5,8.5,0,0,1,12.5,20a8.386,8.386,0,0,1-3.8-.9L3,21l1.9-5.7A8.386,8.386,0,0,1,4,11.5,8.5,8.5,0,0,1,8.7,3.9,8.386,8.386,0,0,1,12.5,3H13a8.48,8.48,0,0,1,8,8Z" />)
