// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const MessageSquare = createIcon(
  'MessageSquare',
  <path d="M21,15a2,2,0,0,1-2,2H7L5,19,3,21V5A2,2,0,0,1,5,3H19a2,2,0,0,1,2,2V15Z" />,
)
