// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Minimize = createIcon('Minimize', <path d="M8.3,3V8.3H3M8.3,21V15.7H3M15.7,3V8.3H21m0,7.4H15.7V21" />)
