// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Minimize2 = createIcon('Minimize2', <path d="M14,10l7-7M10,14,3,21M20,10H14V4M4,14h6v6" />)
