// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const MinusSquare = createIcon(
  'MinusSquare',
  <path d="M8.3,12h7.4M21,19a2.006,2.006,0,0,1-2,2H5a2.006,2.006,0,0,1-2-2V5A2.006,2.006,0,0,1,5,3H19a2.006,2.006,0,0,1,2,2Z" />,
)
