// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Monitor = createIcon(
  'Monitor',
  <path d="M12,21V16.6H4.8A1.8,1.8,0,0,1,3,14.8V4.8A1.8,1.8,0,0,1,4.8,3H19.2A1.8,1.8,0,0,1,21,4.8v10a1.8,1.8,0,0,1-1.8,1.8H16.432M8.95,21H15.1" />,
)
