// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const MoreVertical = createIcon('MoreVertical', <path d="M11,20a1,1,0,1,1,.293.707A1,1,0,0,1,11,20Zm0-8a1,1,0,1,1,.293.707A1,1,0,0,1,11,12Zm0-8a1,1,0,1,1,.293.707A1,1,0,0,1,11,4Z" />)
