// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const MousePointer = createIcon('MousePointer', <path d="M18.649,18.7m-2.894-7.378L21,9.518,3,3,9.936,21l2.5-6.427L19.35,21" />)
