// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Move = createIcon(
  'Move',
  <path d="M12,21V3M9,6l3-3,3,3m0,12-3,3L9,18M3,12H21M6,15,3,12,6,9M18,9l3,3-3,3" />,
)
