// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Music = createIcon('Music', <path d="M9,18V5L21,3V16M6,15a3,3,0,1,1-3,3A3,3,0,0,1,6,15Zm12-2a3,3,0,1,1-3,3A3,3,0,0,1,18,13Z" />)
