// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Navigation = createIcon('Navigation', <polygon points="3 11.526 21 3 12.474 21 10.579 13.421 3 11.526" />)
