// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Navigation2 = createIcon(
  'Navigation2',
  <polygon points="5.5 21.1 12 2.9 18.5 21.1 12 17.2 5.5 21.1" />,
)
