// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const NodeTree = createIcon(
  'NodeTree',
  <>
    <circle cx="12" cy="19.5" r="2.5" />
    <circle cx="12" cy="4.5" r="2.5" />
    <path d="M4.5 14.5V14a2.006 2.006 0 012-2h11a2.006 2.006 0 012 2v.5M12 9.5v5" />
    <circle cx="19.5" cy="19.5" r="2.5" />
    <circle cx="4.5" cy="19.5" r="2.5" />
  </>,
)
