// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Octagon = createIcon('Octagon', <polygon points="8.274 3 15.726 3 21 8.274 21 15.726 15.726 21 8.274 21 3 15.726 3 8.274 8.274 3" />)
