// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const OfficeBuilding = createIcon(
  'OfficeBuilding',
  <>
    <path d="M9 15.25h0M12 15.25h0M15 15.25h0M9 12.25h0M12 12.25h0M15 12.25h0M9 9.25h0M12 9.25h0M15 9.25h0M9 6.25h0M12 6.25h0M15 6.25h0M12 19.25v2.656" />
    <rect x="5" y="2" width="14" height="20" rx="2" ry="2" />
  </>,
)
