// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Oncoprint = createIcon(
  'Oncoprint',
  <path d="M20,3H4A.945.945,0,0,0,3,4V20a.945.945,0,0,0,1,1H20a.945.945,0,0,0,1-1V4a.945.945,0,0,0-1-1ZM6.8,6.4v4.3m6.8-4.3v4.3M17,6.4v4.3M6.8,13.6v4.2m3.3-4.2v4.2M17,13.6v4.2" />,
)
