// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Package = createIcon(
  'Package',
  <path d="M12,21,7.8,19.2,3.6,17.4V6.6L7.8,8.4,12,10.2V21Zm0,0,4.2-1.8,4.2-1.8V6.6L16.2,8.4,12,10.2V21ZM20.4,6.6l-2.25-.95L15.9,4.7l-1.95-.85L12,3,7.8,4.8,3.6,6.6M7.8,8.4l3.9-1.7L15.6,5" />,
)
