// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Paperclip = createIcon('Paperclip', <path d="M4.08,11.947l7.488-7.488a4.892,4.892,0,0,1,6.919,0h0a4.893,4.893,0,0,1,0,6.92L9.608,20.258a2.446,2.446,0,0,1-3.459,0h0a2.446,2.446,0,0,1,0-3.46l8.435-8.436" />)
