// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Pause = createIcon(
  'Pause',
  <path d="M10.205,19.033A1.973,1.973,0,0,1,8.238,21h-.9a1.973,1.973,0,0,1-1.967-1.967V4.967A1.973,1.973,0,0,1,7.335,3h.9a1.973,1.973,0,0,1,1.967,1.967ZM18.632,4.967A1.973,1.973,0,0,0,16.665,3h-.9A1.973,1.973,0,0,0,13.8,4.967V19.033A1.973,1.973,0,0,0,15.762,21h.9a1.973,1.973,0,0,0,1.967-1.967Z" />,
)
