// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const PauseCircle = createIcon('PauseCircle', <path d="M21,12a9,9,0,1,1-9-9A9,9,0,0,1,21,12Zm-6.955,3.409V8.864m-3.818,6.545V8.864" />)
