// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Percent = createIcon(
  'Percent',
  <path d="M21,3,3,21m15.144-5.712A2.856,2.856,0,1,0,21,18.144,2.855,2.855,0,0,0,18.144,15.288ZM5.856,3A2.856,2.856,0,1,0,8.712,5.856,2.856,2.856,0,0,0,5.856,3Z" />,
)
