// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const PieChart = createIcon(
  'PieChart',
  <path d="M19.9,16.3a9.493,9.493,0,0,1-3.275,3.4A8.819,8.819,0,0,1,12,21,8.989,8.989,0,0,1,4.288,7.375,9.544,9.544,0,0,1,7.6,4.1M21,12a8.963,8.963,0,0,0-9-9v8.9l4.5.05Z" />,
)
