// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Pill = createIcon(
  'Pill',
  <path d="M4.424,19.576h0a4.822,4.822,0,0,1,0-6.819l8.333-8.333a4.822,4.822,0,0,1,6.819,0h0a4.822,4.822,0,0,1,0,6.819l-8.333,8.333A4.822,4.822,0,0,1,4.424,19.576Zm11.009-4.19L8.614,8.567" />,
)
