// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const PlayCircle = createIcon(
  'PlayCircle',
  <path d="M15.149,12.418a.582.582,0,0,0,0-.9L12.5,9.351,10.253,7.512a.581.581,0,0,0-.949.45v8.012a.581.581,0,0,0,.949.449L12.5,14.584ZM21,12a9,9,0,1,1-9-9A9,9,0,0,1,21,12Z" />,
)
