// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const PlotCurve = createIcon(
  'PlotCurve',
  <path d="M8.7 3c.7 4.8 3.5 10.5 12.3 11M21 21H3V3M3 5h1.6M3 9h1.6M3 13h1.6M3 17h1.6" />,
)
