// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const PlotNeedle = createIcon(
  'PlotNeedle',
  <>
    <path d="M21 21H3V3M3 5h1.6M3 9h1.6M3 13h1.6M3 17h1.6M11 17v4" />
    <circle cx="11" cy="15" r="2" />
    <path d="M17 9v12" />
    <circle cx="17" cy="7" r="2" />
  </>,
)
