// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const PlusCircle = createIcon(
  'PlusCircle',
  <path d="M12,3A9,9,0,1,1,5.636,5.636,8.972,8.972,0,0,1,12,3Zm0,5v8M8,12h8" />,
)
