// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Pocket = createIcon(
  'Pocket',
  <path d="M21,11.118c0,5.453-4.029,9.873-9,9.873s-9-4.42-9-9.873v-6.2A1.915,1.915,0,0,1,4.909,3.009H19.091A1.915,1.915,0,0,1,21,4.918ZM7.866,9.535,12,14.07l4.134-4.535" />,
)
