// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Power = createIcon(
  'Power',
  <path d="M18.236,5.594a8.969,8.969,0,1,1-12.472,0M12,3v8.272" />,
)
