// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Radio = createIcon(
  'Radio',
  <path d="M11.969,14.01A2.01,2.01,0,1,1,13.979,12,2.01,2.01,0,0,1,11.969,14.01ZM18.5,18.223a9,9,0,0,0,0-12.446M16.091,15.81a5.6,5.6,0,0,0,0-7.621M5.472,5.777a9,9,0,0,0,0,12.446M7.884,8.19a5.6,5.6,0,0,0,0,7.621" />,
)
