// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Rectangles = createIcon(
  'Rectangles',
  <>
    <path d="M6.459,20.449V16.505a.614.614,0,0,1,.614-.615h9.854a.614.614,0,0,1,.614.615h0v3.944a.614.614,0,0,1-.614.615H7.073a.614.614,0,0,1-.614-.615Z" />
    <path d="M13.972,12.082H10.028a.615.615,0,0,1-.615-.615h0V3.614A.614.614,0,0,1,10.028,3h3.944a.614.614,0,0,1,.615.614h0v7.853a.615.615,0,0,1-.615.615Z" />
  </>,
)
