// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const RectanglesOverlay = createIcon(
  'RectanglesOverlay',
  <>
    <path d="M10.478,16.361H4.368A1.367,1.367,0,0,1,3,14.993H3V6.207A1.368,1.368,0,0,1,4.368,4.839H19.632A1.368,1.368,0,0,1,21,6.207h0v.954" />
    <path d="M19.632,21.161H15.846a1.368,1.368,0,0,1-1.368-1.368h0V12.529a1.367,1.367,0,0,1,1.368-1.368h3.786A1.367,1.367,0,0,1,21,12.529h0v7.264a1.368,1.368,0,0,1-1.368,1.368Z" />
  </>,
)
