// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const RectangleH = createIcon('RectangleH', <path d="M21,7.607v8.786a1.367,1.367,0,0,1-1.368,1.368H4.368A1.367,1.367,0,0,1,3,16.393H3V7.607A1.367,1.367,0,0,1,4.368,6.239H19.632A1.367,1.367,0,0,1,21,7.607Z" />)
