// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const RectangleV = createIcon(
  'RectangleV',
  <path d="M7.607,3h8.786a1.367,1.367,0,0,1,1.368,1.368h0V19.632A1.367,1.367,0,0,1,16.393,21H7.607a1.367,1.367,0,0,1-1.368-1.368h0V4.368A1.367,1.367,0,0,1,7.607,3Z" />,
)
