// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const RefreshCw = createIcon('RefreshCw', <path d="M21,12c0,4.97-4.03,9-9,9-3.57,0-6.66-2.08-8.11-5.1M20.11,8.1c-1.45-3.02-4.54-5.1-8.11-5.1C7.03,3,3,7.03,3,12M20.11,8.1l.3-2.55.3-2.55M20.11,8.1l-2.7-.55-2.7-.55M3.29,21l.3-2.55.3-2.55,2.7.55,2.7.55" />)
