// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Repeat = createIcon('Repeat', <path d="M17.251,3,21,6.752,17.251,10.5M21,6.759H5.805A2.807,2.807,0,0,0,3,9.566v1.628m3.751,2.35L3,17.3,6.7,21M3,17.289H18.2A2.807,2.807,0,0,0,21,14.481V12.853" />)
