// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Repository = createIcon(
  'Repository',
  <>
    <path d="M22 16v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4M5.966 2.143h12v6h-12z" />
    <path d="M5.966 12h12v6h-12zM9.966 2.143v6M13.966 2.143v6M9.966 12v6M13.966 12v6" />
  </>,
)
