// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Rewind = createIcon('Rewind', <path d="M21,18.6c0,.331-.211.432-.469.225l-8.021-6.445a.465.465,0,0,1,0-.754l8.021-6.445c.258-.207.469-.106.469.225ZM11.679,5.4c0-.331-.211-.432-.469-.225L3.189,11.623a.464.464,0,0,0,0,.754l8.021,6.445c.258.207.469.106.469-.225Z" />)
