// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Root = createIcon(
  'Root',
  <>
    <circle cx="11.995" cy="15.48" r="4" />
    <path d="M1.045 15.48h6.95M15.995 15.48h6.96M11.995 11.48V4.52" />
  </>,
)
