// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const RotateCw = createIcon(
  'RotateCw',
  <path d="M14.7,7l2.7.55,2.7.55.3-2.55L20.7,3m.3,9.7A9.038,9.038,0,0,1,12,21,9.011,9.011,0,1,1,19.5,7" />,
)
