// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const RotateCcw = createIcon('RotateCcw', <path d="M3.05,2.75l.3,2.55.3,2.55,2.7-.55,2.7-.55m-4.8,0a8.954,8.954,0,1,1-1.5,5.7" />)
