// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Rss = createIcon('Rss', <path d="M3.057,11.719m9.231,9.29a10.338,10.338,0,0,0-9.231-9.29M21,21A18,18,0,0,0,3,3m.036,17.964-.08.061.088-.067" />)
