// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Ruler = createIcon('Ruler', <path d="M16.384,2.984l4.632,4.632-13.4,13.4L2.984,16.384Zm-10.9,11.3L7.17,15.977m1.247-4.625.858.859m2.134-3.738,1.672,1.672m1.263-4.607L15.2,6.4" />)
