// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Save = createIcon(
  'Save',
  <path d="M7.356,20.852V13.038h9.288v7.814M7.356,3.069V8.41h8.952M15.907,3H5.079A2.086,2.086,0,0,0,3,5.079V18.921A2.086,2.086,0,0,0,5.079,21H18.921A2.086,2.086,0,0,0,21,18.921V8.093Z" />,
)
