// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Scatter = createIcon('Scatter', <path d="M3,3V21H21M9,6.5V6.4H9m4.5,2.4V8.7h0M12,12.1V12h0m4.9,1.5v-.1h0m-2.8,4.1v-.1h0" />)
