// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Scissors = createIcon('Scissors', <path d="M9,18a3,3,0,1,1-3-3A3,3,0,0,1,9,18ZM6,3A3,3,0,1,0,9,6,3,3,0,0,0,6,3ZM8.065,15.747,21.006,3m-9.439,8.43L8.315,8.181M14.2,14.037l6.808,6.941" />)
