// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ScreenShareOff = createIcon(
  'ScreenShareOff',
  <path d="M11.96,14.131v6.876m.05-9L9.223,14.789m5.574,0L12.01,12M3.019,7.5v6.87c0,1.1.668,2,1.484,2H5.987m14.567-.57A2.372,2.372,0,0,0,21,14.37V5.009a2,2,0,0,0-2-2H7.4m-4.383,0L21.051,21.044" />,
)
