// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ScreenShare = createIcon(
  'ScreenShare',
  <path d="M5.976,16.355H4.491c-.816,0-1.484-.9-1.484-2V5a2,2,0,0,1,2-2H18.993a2,2,0,0,1,2,2v9.361c0,1.1-.667,2-1.484,2H18.022m-6.073-2.242V21M12,12,9.212,14.777M12,11.991l2.787,2.786" />,
)
