// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Send = createIcon('Send', <path d="M21,3,12,6,3,9l4.55,1.45L12.1,11.9l4.45-4.45Zm0,0-3,9-3,9-1.45-4.55L12.1,11.9l4.45-4.45Z" />)
