// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Share2 = createIcon(
  'Share2',
  <path d="M21,5.841a2.8,2.8,0,1,1-2.8-2.8A2.8,2.8,0,0,1,21,5.841ZM18.2,15.4A2.8,2.8,0,1,0,21,18.2,2.8,2.8,0,0,0,18.2,15.4ZM5.8,9.22a2.8,2.8,0,1,0,2.8,2.8A2.8,2.8,0,0,0,5.8,9.22Zm9.6-2.2L8.6,10.571m7,6.6-7-3.8" />,
)
