// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ShoppingBag = createIcon('ShoppingBag', <path d="M3,8.675H21v8a4.354,4.354,0,0,1-4.342,4.341H7.342A4.354,4.354,0,0,1,3,16.679Zm13.073,3.217V7.073a4.073,4.073,0,0,0-8.146,0v4.819" />)
