// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Shuffle = createIcon('Shuffle', <path d="M21,18H18.031a6,6,0,0,1-3.585-1.181M9.341,6.965a6.006,6.006,0,0,0-3.372-1.03H3m0,12.1H5.969A6.031,6.031,0,0,0,12,12h0a6.031,6.031,0,0,1,6.031-6.031H21M18,9l3-3L18,3m.107,18.031,3-3-3-3" />)
