// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Sidebar = createIcon('Sidebar', <path d="M3,5c0-1.1.9-2,2-2h14.1c1.1,0,2,.9,2,2v14.1c0,1.1-.9,2-2,2H5c-1.1,0-2-.9-2-2V5ZM9.7,3v18.1" />)
