// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Sitting = createIcon(
  'Sitting',
  <path d="M11,3a1.792,1.792,0,1,1-1.268.525A1.792,1.792,0,0,1,11,3Zm2.622,8.693a2.223,2.223,0,0,0-2.193-1.862h0A2.1,2.1,0,0,0,9.2,12.053l.752,3.109h7.21l2.328,4.727M4.506,8.045c.245.98-.385-1.744,2.515,10.646h8.11M11.44,21V18.691" />,
)
