// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const SkipForward = createIcon(
  'SkipForward',
  <path d="M14.4,12.524a1,1,0,0,0,0-1.548L9.85,7.25,5.983,4.086A1,1,0,0,0,4.35,4.86V18.64a1,1,0,0,0,1.633.774L9.85,16.25ZM19.15,2.75v18" />,
)
