// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const SkipBack = createIcon(
  'SkipBack',
  <path d="M17.767,19.664A1,1,0,0,0,19.4,18.89V5.11a1,1,0,0,0-1.633-.774L13.9,7.5,9.346,11.226a1,1,0,0,0,0,1.548L13.9,16.5ZM4.6,21V3" />,
)
