// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Slash = createIcon(
  'Slash',
  <path d="M20.991,11.986A8.991,8.991,0,1,1,12,3,8.991,8.991,0,0,1,20.991,11.986ZM5.808,5.794,18.216,18.2" />,
)
