// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Sliders = createIcon('Sliders', <path d="M15.492,15.842H21m-2.754,0V21m0-18v9.16M3,13.871H8.508m-2.754,0V21m0-18v7.189m9-2.031H9.246m2.754,0V3m0,18V11.84" />)
