// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Smartphone = createIcon('Smartphone', <path d="M16.393,21H7.607a1.368,1.368,0,0,1-1.368-1.368V4.368A1.368,1.368,0,0,1,7.607,3h8.786a1.368,1.368,0,0,1,1.368,1.368V19.632A1.368,1.368,0,0,1,16.393,21ZM12,18.232V18.3M10.708,6.1h2.584" />)
