// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Smile = createIcon(
  'Smile',
  <path d="M12,20.991a9.01,9.01,0,1,0-9.009-9.01A9.01,9.01,0,0,0,12,20.991Zm-3.658-7.04a4.86,4.86,0,0,0,3.6,1.8,4.86,4.86,0,0,0,3.6-1.8m-6.3-4.5h.009m5.391,0h.009" />,
)
