// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const SoundWave = createIcon('SoundWave', <path d="M7.75,21V3M4,13.5v-3M16,17.83V6.17M20,14.33v-4.66M11.88,15.5v-7" />)
