// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const SparkleCircle = createIcon('SparkleCircle', <path d="M15.77,14.08c0,3.43-2.78,6.2-6.2,6.2s-6.2-2.78-6.2-6.2,2.78-6.2,6.2-6.2,6.2,2.78,6.2,6.2ZM16.99,3.23v4.11M20.19,9.08v3.13M19.23,10.65h1.92M15.69,5.28h2.59" />)
