// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const SparkleOutput = createIcon('SparkleOutput', <path d="M5.59,4.23v4.11M9.47,8.86v3.13M8.51,10.43h1.92M4.29,6.28h2.59M21,14.18v4.86c-.14,1.22-1.23,2.11-2.45,2H5.45c-1.22.11-2.31-.78-2.45-2v-4.86M14,16.18v-7.16c0-1.54,1.25-2.79,2.79-2.79h4.21M17.71,2.95l3.29,3.28M17.71,9.52l3.29-3.29" />)
