// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const SparkleFilter = createIcon('SparkleFilter', <path d="M3,4.88h11.71M5.15,9.43h6.74M7.6,14.28h8.8M9.06,19.12h5.87M19.71,2.82v4.11M15.89,7.87v3.13M14.93,9.44h1.92M18.41,4.87h2.59" />)
