// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const SparkleSelect = createIcon(
  'SparkleSelect',
  <path d="M3,7.3V3h4.3M3,12.5v-1M21,12.5v-1M12.5,21h-1M12.5,3h-1M3,16.7v4.3h4.3M21,7.3V3h-4.3M16.7,21h4.3v-4.3M10.57,7.51v4.11M13.77,13.36v3.13M12.81,14.93h1.92M9.27,9.56h2.59" />,
)
