// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const SparkleHeart = createIcon(
  'SparkleHeart',
  <path d="M19.616,5.673a4.738,4.738,0,0,0-6.7,0L12,6.586l-.913-.913a4.739,4.739,0,0,0-6.7,6.7l.913.913,6.7,6.7,6.7-6.7.913-.913a4.738,4.738,0,0,0,0-6.7ZM15.51,7.48v4.11M12.31,13.33v3.13M13.27,14.9h-1.92M16.81,9.53h-2.59" />,
)
