// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Speaker = createIcon(
  'Speaker',
  <path d="M19.33,19.394a1.623,1.623,0,0,1-1.618,1.619H6.288A1.623,1.623,0,0,1,4.67,19.394V4.62A1.623,1.623,0,0,1,6.288,3H17.712A1.623,1.623,0,0,1,19.33,4.62ZM12,10.661a3.526,3.526,0,1,0,3.525,3.525A3.525,3.525,0,0,0,12,10.661Zm0-3.927v.009" />,
)
