// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Split = createIcon('Split', <path d="M3,4.9c0-1.1.9-2,1.9-2h14.1c1.1,0,2,.9,2,2v14.1c0,1.1-.9,2-2,2H5c-1.1,0-2-.9-2-2,0,0,0-14.1,0-14.1ZM12,3v18" />)
