// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const StackedBar = createIcon('StackedBar', <path d="M18 14v-4M18 20v-2M12 12V4M12 20v-4M6 15v-1M6 20v-1" />)
