// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Steps = createIcon('Steps', <path d="M16.851,4.551V9.517H6.877v4.966H13.2V9.517H10.526V4.551H21v14.9H9.325V14.483H3v4.966H9.325" />)
