// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Sunrise = createIcon('Sunrise', <path d="M15.988,7.4l-2.05-2.2L11.888,3v8.3m0-8.3-2,2.2-2,2.2M3,21.02H21M3,17.958H4.75m14.546,0h1.75M16.906,12l1.381-1.382M5.462,10.506l1.381,1.381m1.069,6.071a4,4,0,0,1,8,0" />)
