// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Tablet = createIcon(
  'Tablet',
  <path d="M12,17.276v.01M4.166,19.127A1.87,1.87,0,0,0,6.03,20.991H17.97a1.87,1.87,0,0,0,1.864-1.864V4.864A1.87,1.87,0,0,0,17.97,3H6.03A1.87,1.87,0,0,0,4.166,4.864Z" />,
)
