// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Thermometer = createIcon('Thermometer', <path d="M16.232,16.768A4.232,4.232,0,1,1,9.678,13.25a.96.96,0,0,0,.411-.807V4.957a1.912,1.912,0,1,1,3.822,0v7.486a.958.958,0,0,0,.41.806A4.2,4.2,0,0,1,16.232,16.768Z" />)
