// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ThumbsDown = createIcon(
  'ThumbsDown',
  <path d="M7.643,3H4A1,1,0,0,0,3,4v7.9a1,1,0,0,0,1,1H7.643c1.554,1.8,2.046,5.02,2.9,7.133a1.542,1.542,0,0,0,2.91-.141c.463-1.6,0-5.192,0-5.192H18.5a2.5,2.5,0,0,0,2.414-3.164l-1.7-6.192A3.185,3.185,0,0,0,16.141,3h-8.5v9.9" />,
)
