// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ToggleRight = createIcon(
  'ToggleRight',
  <path d="M16.75,16.2H7.15A4.225,4.225,0,0,1,2.95,12h0a4.224,4.224,0,0,1,4.2-4.2h9.7a4.225,4.225,0,0,1,4.2,4.2h0a4.432,4.432,0,0,1-1.325,2.962A4.238,4.238,0,0,1,16.75,16.2Zm.3-8.2a4,4,0,1,1-2.828,1.172A3.984,3.984,0,0,1,17.05,8Z" />,
)
