// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Tool = createIcon('Tool', <path d="M18.423,8.519l2.158-2.158a5.5,5.5,0,0,1-7.206,7.206L6.281,20.661a1.19,1.19,0,0,1-1.677,0L3.482,19.539a1.191,1.191,0,0,1,0-1.678l7.051-7.05a5.491,5.491,0,0,1,7.291-7.292L14.9,6.441a1.985,1.985,0,0,0,0,2.8h0a1.985,1.985,0,0,0,2.8,0l.721-.721" />)
