// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const TrendingDown = createIcon(
  'TrendingDown',
  <path d="M21,14.6l-.8,3.2L19.4,21l-2.95-5.95L13.5,9.1l-2.65,2.1L8.2,13.3,5.6,8.15,3,3M19.4,21l-3.15-1.25L13.1,18.5" />,
)
