// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const TrendingUp = createIcon(
  'TrendingUp',
  <path d="M3,21l2.6-5.15L8.2,10.7l2.65,2.1,2.65,2.1,2.95-5.95L19.4,3l.8,3.2L21,9.4M13.1,5.5l3.15-1.25L19.4,3" />,
)
