// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Trophy = createIcon('Trophy', <path d="M16.915,3v8.191a5.029,5.029,0,0,1-4.99,5.145,5.032,5.032,0,0,1-4.84-5.145V3m9.83,8.219h2.022A2.063,2.063,0,0,0,21,9.156h0a2.064,2.064,0,0,0-2.063-2.064H16.915m-9.83,0H5.063A2.064,2.064,0,0,0,3,9.156H3a2.063,2.063,0,0,0,2.063,2.063H7.085m4.927,5.155V21M9.151,21h5.668M4.895,3h14.21" />)
