// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Twitter = createIcon(
  'Twitter',
  <path d="M21,4.668a8.9,8.9,0,0,1-1.234.729,8.946,8.946,0,0,1-1.335.522A3.666,3.666,0,0,0,12,8.374v.818A8.721,8.721,0,0,1,4.636,5.486S1.364,12.849,8.727,16.122A9.521,9.521,0,0,1,3,17.759c7.056,3.92,15.615.327,16.317-8.259" />,
)
