// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Twitch = createIcon(
  'Twitch',
  <path d="M17.981,17.746H11.536L7.635,21V17.746H2.921V3H21V14.832Zm-1.8-10.509v4.4m-5.249-4.4v4.4" />,
)
