// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Type = createIcon('Type', <path d="M12,4V20M4,6.133V4H20V6.133M8.089,20h7.822" />)
