// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Underline = createIcon('Underline', <path d="M18.485,3v7.469a6.485,6.485,0,0,1-12.97,0V3m-.98,18h14.93" />)
