// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const UserMinus = createIcon(
  'UserMinus',
  <path d="M11.5,3A3.5,3.5,0,1,1,9.025,4.025,3.493,3.493,0,0,1,11.5,3Zm4.3,11.2a6.9,6.9,0,0,0-2-.9,8.658,8.658,0,0,0-2.3-.3,8.024,8.024,0,0,0-8,8h16m-4.3-3.4h5.3" />,
)
