// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const UserCheck = createIcon(
  'UserCheck',
  <path d="M11.5,3A3.5,3.5,0,1,1,9.025,4.025,3.493,3.493,0,0,1,11.5,3Zm4.7,11.5a7.841,7.841,0,0,0-4.7-1.6,8.024,8.024,0,0,0-8,8h7.1m2.8-1.8,1.05.95L15.5,21,18,18l2.5-3" />,
)
