// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const UserX = createIcon(
  'UserX',
  <path d="M11.5,3A3.5,3.5,0,1,1,9.025,4.025,3.493,3.493,0,0,1,11.5,3ZM14,13.325a7.722,7.722,0,0,0-2.5-.425,8.024,8.024,0,0,0-8,8h9.4m5.583-2.418,1.259,1.259L21,21m-5.037,0,1.26-1.259,1.259-1.259m0,0-1.259-1.259-1.26-1.26m5.037,0-1.259,1.26-1.259,1.259" />,
)
