// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const UserPlus = createIcon(
  'UserPlus',
  <path d="M11.5,3A3.5,3.5,0,1,1,9.025,4.025,3.493,3.493,0,0,1,11.5,3Zm2.3,10.3a7.623,7.623,0,0,0-1.112-.225A9.333,9.333,0,0,0,11.5,13a8.024,8.024,0,0,0-8,8h10m3.7-6.7V21m3.3-3.3H13.8" />,
)
