// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Versions = createIcon(
  'Versions',
  <>
    <rect x="2" y="9" width="20" height="14" rx="2" />
    <path d="M19 5H5M16 1H8" />
  </>,
)
