// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const VerticalArrows = createIcon('VerticalArrows', <path d="M11.988,20.989V3.007m.006,17.977L14.775,18.2m-2.781,2.791L9.2,18.213m2.786-15.2-2.762,2.8m2.762-2.811L14.8,5.767" />)
