// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Video2 = createIcon(
  'Video2',
  <path d="M13.85,18.29H5.269A2.269,2.269,0,0,1,3,16.02V7.98A2.269,2.269,0,0,1,5.269,5.71H13.85a2.269,2.269,0,0,1,2.269,2.27v8.04A2.269,2.269,0,0,1,13.85,18.29Zm2.269-4.584,4.881,2V8.294l-4.881,2" />,
)
