// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Video = createIcon(
  'Video',
  <path d="M12.562,15.116H5a2,2,0,0,1-2-2V6.029a2,2,0,0,1,2-2h7.562a2,2,0,0,1,2,2v7.087A2,2,0,0,1,12.562,15.116Zm0,4.855L8.781,15.116,5,19.971m12.961-8.435H21V7.608H17.961M6.868,7.74v.071" />,
)
