// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Voicemail = createIcon('Voicemail', <path d="M21.005,12A3.746,3.746,0,1,1,17.26,8.255,3.745,3.745,0,0,1,21.005,12ZM6.73,8.255A3.745,3.745,0,1,0,10.476,12,3.745,3.745,0,0,0,6.73,8.255Zm10.658,7.49H6.635" />)
