// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const Wifi = createIcon(
  'Wifi',
  <path d="M3,9.3a12.635,12.635,0,0,1,18,.191m-2.958,2.959a8.452,8.452,0,0,0-12.087-.192m9.1,3.177a4.226,4.226,0,0,0-6.122-.2M12,18.306V18.3" />,
)
