// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const X2 = createIcon(
  'X2',
  <path d="M7.75735 7.75736L16.2426 16.2426M16.2426 7.75736L7.75735 16.2426" />,
)
