// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const X3 = createIcon(
  'X3',
  <path d="M8.46446 8.46447L15.5355 15.5355M15.5355 8.46447L8.46446 15.5355" />,
)
