// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const XCircle = createIcon(
  'XCircle',
  <path d="M12,3A9,9,0,1,1,5.636,5.636,8.972,8.972,0,0,1,12,3ZM9,9l3,3,3,3m0-6-3,3L9,15" />,
)
