// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const XOctogon = createIcon('XOctogon', <path d="M12,12l1.678,1.679,1.679,1.679m-6.715,0,1.679-1.679L12,12m0,0-1.679-1.678L8.638,8.647m6.715,0-1.679,1.679L12,12m3.723-8.983H8.281l-5.26,5.26v7.438l5.26,5.26h7.438l5.26-5.26V8.281Z" />)
