// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const XSquare = createIcon('XSquare', <path d="M12,12l1.678,1.679,1.679,1.679m-6.715,0,1.679-1.679L12,12m0,0-1.679-1.678L8.638,8.647m6.715,0-1.679,1.679L12,12m9-6.557A2.454,2.454,0,0,0,18.551,3H5.447A2.454,2.454,0,0,0,3,5.446v13.1A2.454,2.454,0,0,0,5.447,21l13.108,0A2.452,2.452,0,0,0,21,18.554Z" />)
