// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ZapOff = createIcon('ZapOff', <path d="M12.456,6.6l.45-3.6m5.431,9.323L20.106,10.2h-4.05M8.206,8.7l-2.15,2.55L3.906,13.8h8.1l-.45,3.6-.45,3.6,4.5-5.4M12.906,3,11.162,5.118M3,3.012,21.008,21" />)
