// GENERATED by scripts/icons/generate.mjs — do not edit by hand.
import { createIcon } from '../create-icon'

export const ZoomIn = createIcon('ZoomIn', <path d="M10.1,3A7.1,7.1,0,1,1,5.08,5.08,7.074,7.074,0,0,1,10.1,3ZM21,21l-2.9-2.9-2.9-2.9M10.1,7.1v6m3-3h-6" />)
