/**
 * Icon generator.
 *
 * Reads the vendored chromicons SVG source (packages/icons/svg/*.svg, MIT —
 * see NOTICE) and emits packages/icons/src/generated.tsx: one `createIcon`
 * export per icon. Each source SVG is normalized — the presentation
 * attributes `createIcon` already supplies (stroke/fill/stroke-width/
 * stroke-linecap/stroke-linejoin/stroke-miterlimit/class) are stripped, the
 * inner geometry is kept, and the kebab-case filename is mapped to PascalCase.
 * Names that collide with the existing hand-authored Feather-derived set are
 * skipped — the existing export always wins, so v45 is purely additive.
 *
 * Mirrors the tokens pipeline (scripts/catalog/generate.ts → tokens.catalog.json).
 * Deterministic + idempotent: a second run produces no diff.
 *
 * Run with: `pnpm icons:generate`
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..', '..')
const SVG_DIR = join(ROOT, 'packages/icons/svg')
const OUT_TSX = join(ROOT, 'packages/icons/src/generated.tsx')

/**
 * The 60 hand-authored Feather-derived icons already exported from index.tsx.
 * On a name collision the existing export wins, so these chromicons are skipped.
 * Keep this list in sync with the inline exports in packages/icons/src/index.tsx.
 */
const EXISTING = new Set([
  'Activity', 'AlertCircle', 'AlertTriangle', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'ArrowUp',
  'BarChart', 'Bell', 'Calendar', 'Check', 'CheckCircle', 'ChevronDown', 'ChevronLeft',
  'ChevronRight', 'ChevronUp', 'Clock', 'Copy', 'CreditCard', 'Dashboard', 'Database', 'Download',
  'Edit', 'ExternalLink', 'Eye', 'EyeOff', 'File', 'Filter', 'Folder', 'Globe', 'Grid', 'Heart',
  'HelpCircle', 'Home', 'Inbox', 'Info', 'Key', 'Layers', 'Loader', 'Lock', 'LogOut', 'Menu',
  'Minus', 'Moon', 'MoreHorizontal', 'Plus', 'Search', 'Server', 'Settings', 'Shield', 'Star',
  'Sun', 'Tag', 'Terminal', 'Trash', 'Upload', 'User', 'Users', 'X', 'Zap',
])

/** Presentation attributes createIcon already supplies — stripped from inner geometry. */
const STRIP_ATTRS = [
  'stroke-width',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-miterlimit',
  'stroke',
  'fill',
  'class',
  'data-name',
  'id',
]

/** `alert-circle` → `AlertCircle`. */
function toPascalCase(kebab) {
  return kebab
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
}

/** Strip a single self-closed element down to geometry-only, JSX-ready. */
function cleanElement(el) {
  let out = el
  for (const attr of STRIP_ATTRS) {
    out = out.replace(new RegExp(`\\s+${attr}="[^"]*"`, 'g'), '')
  }
  // kebab attr → camelCase (none survive the strip today, but keep it robust)
  out = out.replace(/\s([a-z]+)-([a-z]+)=/g, (_m, a, b) => ` ${a}${b.charAt(0).toUpperCase()}${b.slice(1)}=`)
  out = out.replace(/\s+/g, ' ').replace(/\s*\/>$/, ' />')
  return out
}

/** Extract + normalize the inner geometry of one source SVG. */
function normalize(svg, file) {
  const match = svg.match(/<svg[^>]*viewBox="0 0 24 24"[^>]*>([\s\S]*?)<\/svg>/)
  if (!match) {
    throw new Error(`${file}: not a viewBox="0 0 24 24" SVG (off-grid icons are rejected)`)
  }
  const elements = match[1].match(/<[a-zA-Z][^>]*?\/>/g)
  if (!elements || elements.length === 0) {
    throw new Error(`${file}: no geometry elements found`)
  }
  return elements.map(cleanElement)
}

/** Emit the `createIcon(...)` body for an icon's normalized elements. */
function renderChildren(elements) {
  if (elements.length === 1) {
    return elements[0]
  }
  return `<>\n    ${elements.join('\n    ')}\n  </>`
}

function main() {
  const files = readdirSync(SVG_DIR)
    .filter((f) => f.endsWith('.svg'))
    .sort()

  const icons = []
  let skipped = 0
  for (const file of files) {
    const pascal = toPascalCase(file.replace(/\.svg$/, ''))
    if (EXISTING.has(pascal)) {
      skipped++
      continue
    }
    const elements = normalize(readFileSync(join(SVG_DIR, file), 'utf8'), file)
    icons.push({ pascal, elements })
  }
  icons.sort((a, b) => a.pascal.localeCompare(b.pascal))

  const lines = [
    '// GENERATED by scripts/icons/generate.mjs — do not edit by hand.',
    '// Geometry: chromicons (MIT). See NOTICE. Run `pnpm icons:generate` to refresh.',
    "import { createIcon } from './create-icon'",
    '',
  ]
  for (const { pascal, elements } of icons) {
    if (elements.length === 1) {
      lines.push(`export const ${pascal} = createIcon('${pascal}', ${elements[0]})`)
    } else {
      lines.push(`export const ${pascal} = createIcon(`)
      lines.push(`  '${pascal}',`)
      lines.push(`  ${renderChildren(elements)},`)
      lines.push(')')
    }
  }
  writeFileSync(OUT_TSX, lines.join('\n') + '\n')
  console.log(`Wrote ${icons.length} icons to packages/icons/src/generated.tsx (${skipped} skipped as collisions)`)
}

main()
