#!/usr/bin/env node
/**
 * Migration-guide table generator.
 *
 * Reads apps/site/public/parity.json (itself generated + verified by
 * scripts/parity/generate.ts, so a component only appears as covered when it is
 * genuinely shipped and exported) and injects a shadcn/ui → cascivo mapping
 * table into docs/MIGRATING-FROM-SHADCN.md between the markers:
 *
 *   <!-- BEGIN shadcn-map (generated by scripts/migration/generate.ts) -->
 *   <!-- END shadcn-map -->
 *
 * Keeping the table generated means it can never overstate coverage or drift
 * from reality. Run with: `pnpm migration:generate` (part of `pnpm regen`,
 * after `parity:generate`).
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(import.meta.dirname, '../..')
const PARITY = join(ROOT, 'apps/site/public/parity.json')
const REGISTRY = join(ROOT, 'registry.json')
const GUIDE = join(ROOT, 'docs/MIGRATING-FROM-SHADCN.md')
const DOCS = 'https://cascivo.com/docs/components'

const esc = (s: string) => s.replace(/\|/g, '\\|')

// Real component slugs, so we only link to doc pages that actually resolve — a
// parity row may map to a category ("chart") that has no bare component page.
const registrySlugs = new Set(
  (JSON.parse(readFileSync(REGISTRY, 'utf8')) as { components: { name: string }[] }).components.map(
    (c) => c.name,
  ),
)

function cascivoCell(slug: string): string {
  return registrySlugs.has(slug) ? `[\`${esc(slug)}\`](${DOCS}/${slug})` : `\`${esc(slug)}\``
}

const BEGIN = '<!-- BEGIN shadcn-map (generated by scripts/migration/generate.ts) -->'
const END = '<!-- END shadcn-map -->'

type Row = { competitor: string; status: string; cascivo: string; note: string }
type Parity = {
  competitors: { shadcn: { total: number; covered: number; rows: Row[] } }
}

function buildTable(): string {
  const parity = JSON.parse(readFileSync(PARITY, 'utf8')) as Parity
  const shadcn = parity.competitors.shadcn
  const lines: string[] = []

  lines.push(
    `_Generated from the [parity matrix](https://cascivo.com/docs/parity) — ${shadcn.covered} of ${shadcn.total} shadcn/ui components have a cascivo equivalent. Each cascivo link carries the exact \`cascivo add\` command._`,
  )
  lines.push('')
  lines.push('| shadcn/ui | cascivo | Notes |')
  lines.push('| --------- | ------- | ----- |')

  for (const row of [...shadcn.rows].sort((a, b) => a.competitor.localeCompare(b.competitor))) {
    const note = esc(row.note ?? '')
    let cascivo: string
    if (row.cascivo) {
      cascivo = cascivoCell(row.cascivo)
    } else if (row.status === 'by-convention') {
      cascivo = '_by convention_'
    } else {
      cascivo = '—'
    }
    lines.push(`| ${esc(row.competitor)} | ${cascivo} | ${note} |`)
  }

  return lines.join('\n')
}

function main(): void {
  const guide = readFileSync(GUIDE, 'utf8')
  const beginIdx = guide.indexOf(BEGIN)
  const endIdx = guide.indexOf(END)
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    throw new Error(
      `Markers not found in ${GUIDE}. Expected:\n  ${BEGIN}\n  ${END}\n(placed around the mapping table).`,
    )
  }
  const before = guide.slice(0, beginIdx + BEGIN.length)
  const after = guide.slice(endIdx)
  const next = `${before}\n\n${buildTable()}\n\n${after}`
  if (next !== guide) {
    writeFileSync(GUIDE, next, 'utf8')
  }
  console.log(`Wrote shadcn→cascivo map into ${GUIDE.replace(ROOT + '/', '')}`)
}

main()
