#!/usr/bin/env node
/**
 * Generates the react <-> icons collision list into `docs/RECIPE-DASHBOARD.md`.
 *
 * The react <-> charts collisions got a table and a CI guard; react <-> icons got one
 * sentence saying the two "share names by nature" and never said WHICH names. `Search` is the
 * sharp one — a first-tier component and a first-tier icon, both valid JSX in the same
 * position, so a wrong import resolves silently rather than failing to compile. An adopter
 * shipped `Search` (component) in one file and `Search` (icon) in another and noted they were
 * "one refactor away from a silent wrong import" (2026-08-31 report §25).
 *
 * Generated rather than hand-written because the set moves with every icon and component
 * added. `scripts/checks/export-collisions.test.ts` fails when this block is stale.
 *
 * Run with: `pnpm collisions:generate`
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { collidingIconNames, BEGIN, END } from '../checks/lib/collisions.ts'

const ROOT = fileURLToPath(new URL('../..', import.meta.url))
const DOC = join(ROOT, 'docs/RECIPE-DASHBOARD.md')

function render(names: string[]): string {
  const rows = names.map(
    (n) => `| \`${n}\` | \`import { ${n} as ${n}Icon } from '@cascivo/icons'\` |`,
  )
  return [
    BEGIN,
    `<!-- Generated by scripts/docs-md/collisions.ts — run \`pnpm collisions:generate\`. -->`,
    '',
    `These ${names.length} names exist in **both** \`@cascivo/icons\` and a component package`,
    '(`@cascivo/react` or `@cascivo/charts`). Both are valid JSX in the same position, so a',
    'wrong import resolves silently instead of failing to compile — alias the icon:',
    '',
    '| Name | Alias the icon as |',
    '| --- | --- |',
    ...rows,
    '',
    END,
  ].join('\n')
}

const doc = readFileSync(DOC, 'utf8')
const start = doc.indexOf(BEGIN)
const end = doc.indexOf(END)
if (start === -1 || end === -1) {
  throw new Error(`docs/RECIPE-DASHBOARD.md is missing the ${BEGIN} / ${END} markers`)
}
const next = doc.slice(0, start) + render(collidingIconNames(ROOT)) + doc.slice(end + END.length)
writeFileSync(DOC, next)
console.log(`Wrote the react <-> icons collision table to docs/RECIPE-DASHBOARD.md`)
