import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../..', import.meta.url))

interface Pkg {
  name: string
  description?: string
  private?: boolean
}

const MARKER =
  '<!-- generated by scripts/readme/generate.ts — edit readme.body.md, not this file -->'

const LOGO = 'https://cascivo.com/favicon.svg'
const BRAND = '0079bf'
const AI = '8b5cf6'

const TAGLINE = 'The CSS-native, signal-driven, AI-first React design system'

const SITE_LINKS =
  '[cascivo.com](https://cascivo.com) · [Docs](https://docs.cascivo.com) · [Storybook](https://storybook.cascivo.com) · [GitHub](https://github.com/cascivo/cascivo)'

const FOOTER = `---

${SITE_LINKS} · AI agents: read [\`llms.txt\`](https://cascivo.com/llms.txt) (install steps + component index, plain text) or use [\`@cascivo/mcp\`](https://github.com/cascivo/cascivo/tree/main/packages/mcp) and [\`registry.json\`](https://github.com/cascivo/cascivo/blob/main/registry.json) · MIT

<div align="center"><a href="https://cascivo.com"><img src="${LOGO}" width="28" height="28" alt="cascivo"></a></div>
`

function badge(label: string, message: string, color: string, opts?: { logo?: string }): string {
  const logo = opts?.logo ? `&logo=${opts.logo}&logoColor=white` : ''
  return `![${label}](https://img.shields.io/badge/${label}-${message}-${color}?style=flat-square${logo})`
}

function rootBadges(componentCount: number, themeCount: number): string {
  return [
    `[![CI](https://img.shields.io/github/actions/workflow/status/cascivo/cascivo/ci.yml?branch=main&style=flat-square&label=CI)](https://github.com/cascivo/cascivo/actions/workflows/ci.yml)`,
    `[![npm](https://img.shields.io/npm/v/cascivo?style=flat-square&color=${BRAND}&label=cascivo)](https://www.npmjs.com/package/cascivo)`,
    `[![license](https://img.shields.io/github/license/cascivo/cascivo?style=flat-square&color=${BRAND})](https://github.com/cascivo/cascivo/blob/main/LICENSE)`,
    `[${badge('TypeScript', 'strict', BRAND, { logo: 'typescript' })}](https://www.typescriptlang.org/)`,
    `[${badge('React', '18%2B', BRAND, { logo: 'react' })}](https://react.dev/)`,
    badge('CSS', 'native', BRAND, { logo: 'css3' }),
    badge('components', String(componentCount), BRAND),
    badge('themes', String(themeCount), BRAND),
    badge('WCAG_2.2', 'AA', BRAND),
    `[${badge('AI--first', 'MCP', AI)}](https://github.com/cascivo/cascivo/tree/main/packages/mcp)`,
  ].join('\n  ')
}

// Bundles and interop sheets that are not selectable themes. Keep in sync with
// NON_THEME_CSS in apps/site/vite.config.ts.
const NON_THEME_CSS = new Set(['all.css', 'base.css', 'tailwind.css'])

interface Counts {
  components: number
  charts: number
  themes: number
}

function readCounts(): Counts {
  const registry = JSON.parse(readFileSync(join(root, 'registry.json'), 'utf8')) as {
    components: { type?: string }[]
  }
  const themes = readdirSync(join(root, 'packages/themes/src')).filter(
    (f) => f.endsWith('.css') && !NON_THEME_CSS.has(f),
  ).length
  return {
    components: registry.components.length,
    charts: registry.components.filter((c) => c.type === 'chart').length,
    themes,
  }
}

// Replace {{count.components}} / {{count.charts}} / {{count.themes}} in
// readme.body.md content so hand-written prose can never drift from the
// registry again. Fails hard on unknown placeholders.
function substituteCounts(body: string, counts: Counts, source: string): string {
  const out = body.replaceAll(/\{\{count\.(\w+)\}\}/g, (_, key: string) => {
    const value = counts[key as keyof Counts]
    if (value === undefined)
      throw new Error(`Unknown count placeholder {{count.${key}}} in ${source}`)
    return String(value)
  })
  if (out.includes('{{count.')) throw new Error(`Unresolved count placeholder left in ${source}`)
  return out
}

function packageBadges(pkg: Pkg, installable: boolean): string {
  const encoded = encodeURIComponent(pkg.name)
  const out: string[] = []
  if (installable) {
    out.push(
      `[![npm](https://img.shields.io/npm/v/${encoded}?style=flat-square&color=${BRAND})](https://www.npmjs.com/package/${pkg.name})`,
      `[![downloads](https://img.shields.io/npm/dm/${encoded}?style=flat-square&color=${BRAND})](https://www.npmjs.com/package/${pkg.name})`,
      `[![license](https://img.shields.io/npm/l/${encoded}?style=flat-square&color=${BRAND})](https://github.com/cascivo/cascivo/blob/main/LICENSE)`,
    )
  } else {
    out.push(badge('workspace', 'private', '64748b'))
  }
  out.push(badge('types', 'included', BRAND, { logo: 'typescript' }))
  return out.join('\n  ')
}

function header(title: string, tagline: string, badges: string, links: string): string {
  return [
    '<div align="center">',
    `  <a href="https://cascivo.com"><img src="${LOGO}" width="72" height="72" alt="cascivo logo"></a>`,
    `  <h1>${title}</h1>`,
    `  <p><strong>${tagline}</strong></p>`,
    '',
    `  ${badges}`,
    '',
    `  ${links}`,
    '</div>',
    '',
    '---',
  ].join('\n')
}

function workspaceDirs(): string[] {
  const groups = ['packages', 'apps', join('apps', 'examples')]
  const dirs: string[] = []
  for (const group of groups) {
    const base = join(root, group)
    if (!existsSync(base)) continue
    for (const entry of readdirSync(base, { withFileTypes: true })) {
      if (entry.isDirectory() && existsSync(join(base, entry.name, 'package.json'))) {
        dirs.push(join(base, entry.name))
      }
    }
  }
  return dirs.sort()
}

function readPkg(dir: string): Pkg {
  return JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as Pkg
}

// Ordered, labelled groups for the published-package tables in the root README.
// Any installable package not listed here lands in a trailing "More" group.
const PUBLISHED_GROUPS: { title: string; names: string[] }[] = [
  {
    title: 'Core & styling',
    names: ['@cascivo/core', '@cascivo/tokens', '@cascivo/themes', '@cascivo/icons'],
  },
  { title: 'Components & charts', names: ['@cascivo/react', '@cascivo/charts', '@cascivo/editor'] },
  { title: 'State & i18n', names: ['@cascivo/i18n', '@cascivo/storage'] },
  { title: 'CLI, registry & AI', names: ['cascivo', '@cascivo/registry', '@cascivo/mcp'] },
]

function relDir(dir: string): string {
  return relative(root, dir).replaceAll('\\', '/')
}

function npmCell(name: string): string {
  const encoded = encodeURIComponent(name)
  return `[![npm](https://img.shields.io/npm/v/${encoded}?style=flat-square&color=${BRAND})](https://www.npmjs.com/package/${name})`
}

function packagesSection(targets: string[]): string {
  const entries = targets.map((dir) => ({ dir, pkg: readPkg(dir) }))
  const byName = new Map(entries.map((e) => [e.pkg.name, e]))
  const inPackages = (dir: string) => dir.startsWith(join(root, 'packages'))
  const isApp = (dir: string) =>
    dir.startsWith(join(root, 'apps')) && !dir.startsWith(join(root, 'apps', 'examples'))
  const isExample = (dir: string) => dir.startsWith(join(root, 'apps', 'examples'))

  const lines: string[] = ['## Packages', '']
  lines.push(
    'Published packages install from npm. Components themselves are copy-pasted into your project via the CLI (you own the source) — see [Quick Start](#quick-start).',
    '',
  )

  const used = new Set<string>()
  for (const group of PUBLISHED_GROUPS) {
    const rows = group.names
      .map((name) => byName.get(name))
      .filter((e): e is { dir: string; pkg: Pkg } => Boolean(e) && e!.pkg.private !== true)
    if (rows.length === 0) continue
    lines.push(`### ${group.title}`, '')
    lines.push('| Package | Version | Description |', '| --- | --- | --- |')
    for (const { dir, pkg } of rows) {
      used.add(pkg.name)
      lines.push(
        `| [\`${pkg.name}\`](${relDir(dir)}) | ${npmCell(pkg.name)} | ${pkg.description ?? ''} |`,
      )
    }
    lines.push('')
  }

  const more = entries.filter(
    (e) => inPackages(e.dir) && e.pkg.private !== true && !used.has(e.pkg.name),
  )
  if (more.length > 0) {
    lines.push('### More', '')
    lines.push('| Package | Version | Description |', '| --- | --- | --- |')
    for (const { dir, pkg } of more) {
      lines.push(
        `| [\`${pkg.name}\`](${relDir(dir)}) | ${npmCell(pkg.name)} | ${pkg.description ?? ''} |`,
      )
    }
    lines.push('')
  }

  const internal = entries.filter((e) => inPackages(e.dir) && e.pkg.private === true)
  if (internal.length > 0) {
    lines.push('### Registry sources & internal packages', '')
    lines.push(
      'Not published to npm. `components` and `layouts` are the source of truth the CLI copies from; the rest power the docs, AI, and search surfaces.',
      '',
    )
    lines.push('| Package | Description |', '| --- | --- |')
    for (const { dir, pkg } of internal) {
      lines.push(`| [\`${pkg.name}\`](${relDir(dir)}) | ${pkg.description ?? ''} |`)
    }
    lines.push('')
  }

  const apps = entries.filter((e) => isApp(e.dir))
  if (apps.length > 0) {
    lines.push('### Apps', '')
    lines.push('| App | Description |', '| --- | --- |')
    for (const { dir, pkg } of apps) {
      lines.push(`| [\`${pkg.name}\`](${relDir(dir)}) | ${pkg.description ?? ''} |`)
    }
    lines.push('')
  }

  const examples = entries.filter((e) => isExample(e.dir))
  if (examples.length > 0) {
    lines.push('### Examples', '')
    lines.push('| Example | Description |', '| --- | --- |')
    for (const { dir, pkg } of examples) {
      lines.push(`| [\`${pkg.name}\`](${relDir(dir)}) | ${pkg.description ?? ''} |`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

function componentsTable(collapsible: boolean): string {
  const registry = JSON.parse(readFileSync(join(root, 'registry.json'), 'utf8')) as {
    components: { name: string; category: string; description: string }[]
  }
  const counts = new Map<string, number>()
  for (const c of registry.components) counts.set(c.category, (counts.get(c.category) ?? 0) + 1)
  const summary = [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([cat, n]) => `${cat} ${n}`)
    .join(' · ')

  const rows = registry.components
    .map((c) => `| ${c.name} | ${c.category} | ${c.description} |`)
    .join('\n')
  const table = `| Name | Category | Description |\n| --- | --- | --- |\n${rows}`

  if (!collapsible) return `## Components\n\n${table}\n`

  // Compact, scannable summary — one line per category listing the names, rather
  // than a ~200-row table. Descriptions + live previews live on the docs site;
  // the full machine-readable index is registry.json. Keeps the README short and
  // keeps every component name greppable/crawlable in the collapsed block.
  const byCategory = new Map<string, string[]>()
  for (const c of registry.components) {
    const list = byCategory.get(c.category) ?? []
    list.push(c.name)
    byCategory.set(c.category, list)
  }
  const categoryLines = [...byCategory.entries()]
    .sort((a, b) => b[1].length - a[1].length)
    .map(([cat, names]) => `**${cat}** (${names.length}) — ${names.sort().join(', ')}`)
    .join('\n\n')

  return [
    '## Components',
    '',
    `**${registry.components.length} components** — ${summary}.`,
    '',
    'Browse the full catalog with live previews at [cascivo.com/docs/components](https://cascivo.com/docs/components), or read the machine index at [registry.json](https://cascivo.com/registry.json).',
    '',
    `<details>`,
    `<summary>All ${registry.components.length} components by category</summary>`,
    '',
    categoryLines,
    '',
    '</details>',
    '',
  ].join('\n')
}

function buildReadme(dir: string, pkg: Pkg, isRoot: boolean, targets: string[]): string {
  const counts = readCounts()

  const installable = !isRoot && pkg.private !== true && dir.startsWith(join(root, 'packages'))
  const title = isRoot ? 'cascivo' : pkg.name
  const tagline = isRoot ? TAGLINE : (pkg.description ?? TAGLINE)
  const badges = isRoot
    ? rootBadges(counts.components, counts.themes)
    : packageBadges(pkg, installable)
  const links = installable
    ? `[npm](https://www.npmjs.com/package/${pkg.name}) · ${SITE_LINKS}`
    : SITE_LINKS

  const sections: string[] = [MARKER, '', header(title, tagline, badges, links), '']

  const bodyPath = join(dir, 'readme.body.md')
  if (existsSync(bodyPath)) {
    sections.push(substituteCounts(readFileSync(bodyPath, 'utf8').trim(), counts, bodyPath), '')
  }

  if (installable) {
    sections.push('## Install', '', '```sh', `pnpm add ${pkg.name}`, '```', '')
  }

  if (isRoot) {
    sections.push(packagesSection(targets), componentsTable(true))
  } else if (pkg.name === '@cascivo/components') {
    sections.push(componentsTable(false))
  }

  sections.push(FOOTER)
  return sections.join('\n')
}

const dirs = workspaceDirs()
const targets = [root, ...dirs]
for (const dir of targets) {
  const pkg = readPkg(dir)
  writeFileSync(join(dir, 'README.md'), buildReadme(dir, pkg, dir === root, dirs))
}
const fmt = spawnSync('pnpm', ['exec', 'vp', 'fmt', '**/README.md'], {
  cwd: root,
  stdio: 'inherit',
})
if (fmt.status !== 0) process.exit(fmt.status ?? 1)
console.log(`Generated ${targets.length} READMEs`)
