import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../..', import.meta.url))

interface Pkg {
  name: string
  description?: string
  private?: boolean
}

const MARKER =
  '<!-- generated by scripts/readme/generate.ts — edit readme.body.md, not this file -->'

function workspaceDirs(): string[] {
  const groups = ['packages', 'apps', join('apps', 'examples')]
  const dirs: string[] = []
  for (const group of groups) {
    const base = join(root, group)
    if (!existsSync(base)) continue
    for (const entry of readdirSync(base, { withFileTypes: true })) {
      if (entry.isDirectory() && existsSync(join(base, entry.name, 'package.json'))) {
        dirs.push(join(base, entry.name))
      }
    }
  }
  return dirs.sort()
}

function componentsTable(): string {
  const registry = JSON.parse(readFileSync(join(root, 'registry.json'), 'utf8')) as {
    components: { name: string; category: string; description: string }[]
  }
  const rows = registry.components
    .map((c) => `| ${c.name} | ${c.category} | ${c.description} |`)
    .join('\n')
  return `## Components\n\n| Name | Category | Description |\n| --- | --- | --- |\n${rows}\n`
}

function buildReadme(dir: string, pkg: Pkg, isRoot: boolean): string {
  const sections: string[] = [MARKER, '']
  sections.push(isRoot ? '# cascade' : `# ${pkg.name}`, '')
  if (pkg.description) sections.push(`> ${pkg.description}`, '')
  const bodyPath = join(dir, 'readme.body.md')
  if (existsSync(bodyPath)) sections.push(readFileSync(bodyPath, 'utf8').trim(), '')
  const installable = !isRoot && pkg.private !== true && dir.startsWith(join(root, 'packages'))
  if (installable) {
    sections.push('## Install', '', '```sh', `pnpm add ${pkg.name}`, '```', '')
  }
  if (isRoot || pkg.name === '@cascivo/react' || pkg.name === '@cascivo/components') {
    sections.push(componentsTable())
  }
  sections.push(
    '---',
    '',
    '[Docs](https://urbanisierung.github.io/cascade-ui/) · AI agents: use [`@cascivo/mcp`](https://github.com/urbanisierung/cascade-ui/tree/main/packages/mcp) and [`registry.json`](https://github.com/urbanisierung/cascade-ui/blob/main/registry.json) · MIT',
    '',
  )
  return sections.join('\n')
}

const targets = [root, ...workspaceDirs()]
for (const dir of targets) {
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as Pkg
  writeFileSync(join(dir, 'README.md'), buildReadme(dir, pkg, dir === root))
}
const fmt = spawnSync('pnpm', ['exec', 'vp', 'fmt', '**/README.md'], {
  cwd: root,
  stdio: 'inherit',
})
if (fmt.status !== 0) process.exit(fmt.status ?? 1)
console.log(`Generated ${targets.length} READMEs`)
