import type { ComponentMeta } from '@cascivo/core'

export const meta: ComponentMeta = {
  name: 'AiBadge',
  description:
    'Small "AI" marker for AI-generated content; with children it opens a toggletip explaining how AI was involved',
  category: 'display',
  // The marker is static markup and reads with JS off. The explanation (Toggletip, its own
  // client boundary) and the revert button need JS.
  clientJs: 'enhancement',
  states: [],
  variants: [],
  sizes: [],
  props: [
    {
      name: 'children',
      description:
        'The explanation shown in the toggletip — model, sources, confidence. Omit for a static marker.',
      type: 'ReactNode',
      required: false,
    },
    {
      name: 'edited',
      description:
        'The person has changed the AI’s output. The AI mark gives way to a revert button when `onRevert` is set, and to nothing otherwise — edited content is no longer AI-generated.',
      type: 'boolean',
      required: false,
      default: 'false',
    },
    {
      name: 'onRevert',
      description:
        'Restores the AI version. Shown as an icon button (named by `labels.revert`) while `edited` is true.',
      type: '() => void',
      required: false,
    },
    {
      name: 'labels',
      description:
        'Overrides for the component’s user-visible strings (i18n): `text` (the pill, "AI"), `explain` (appended to the trigger’s accessible name), `description` (what a screen reader hears for the static marker), `revert` (the revert button’s accessible name).',
      type: '{ text?: string; explain?: string; description?: string; revert?: string }',
      required: false,
    },
  ],
  tokens: [
    '--cascivo-color-ai',
    '--cascivo-color-ai-subtle',
    '--cascivo-color-ai-border',
    '--cascivo-color-text',
    '--cascivo-radius-indicator',
    '--cascivo-text-xs',
    '--cascivo-font-semibold',
  ],
  accessibility: {
    role: 'button',
    wcag: '2.2-AA',
    keyboard: ['Enter', 'Space', 'Escape'],
    forcedColors: true,
  },
  examples: [
    {
      title: 'Edited, with revert',
      code: '<AiBadge edited onRevert={() => {}} />',
    },
    { title: 'Static marker', code: '<AiBadge />' },
    {
      title: 'With explanation',
      code: '<AiBadge>This summary was generated by an AI model from the last 30 days of tickets. Check important details.</AiBadge>',
    },
  ],
  dependencies: ['@cascivo/core', '@cascivo/i18n'],
  registryDependencies: ['icon-button', 'toggletip', 'visually-hidden'],
  tags: ['ai', 'label', 'badge', 'provenance', 'explainability', 'generated'],
  intent: {
    whenToUse: [
      'Marking a field, card, table cell or message whose content an AI produced or suggested',
      'Giving readers an on-demand explanation of how AI was involved (model, sources, confidence)',
      'Offering a way back to the AI version after a person edits an AI-filled value (`edited` + `onRevert`)',
    ],
    whenNotToUse: [
      'Reporting that generation is in progress — use AiStatus',
      'Generic status or category chips — use Badge or Tag',
    ],
    antiPatterns: [
      {
        bad: 'A sparkle icon alone next to AI content',
        good: '<AiBadge /> — visible "AI" text and an accessible description',
        why: 'An icon or gradient carries no meaning for assistive tech; the badge names the provenance',
      },
    ],
    related: [
      {
        name: 'Toggletip',
        relationship: 'contains',
        reason: 'The explanation opens in a Toggletip anchored to the badge',
      },
      {
        name: 'Badge',
        relationship: 'alternative',
        reason: 'Badge is the general-purpose chip; AiBadge is reserved for AI provenance',
      },
      {
        name: 'AiStatus',
        relationship: 'pairs-with',
        reason: 'AiStatus reports work in progress; AiBadge marks the finished result',
      },
    ],
    a11yRationale:
      'Provenance is carried by text, never by colour: the static marker shows "AI" and reads "AI-generated"; the interactive one is a button whose accessible name begins with its visible text ("AI Show information", WCAG 2.5.3), opening a Toggletip that is dismissable with Escape. The revert state is a real button with an accessible name ("Revert to AI suggestion"). Forced colours keep the border and text as CanvasText',
    content: {
      tone: 'Plain and factual — say what the AI did and what the reader should check',
      notes: 'Keep the pill to "AI" (localised); put detail in the explanation',
    },
    flexibility: [
      {
        area: 'explanation content',
        level: 'flexible',
        note: 'Any rich content — model name, sources, a link to learn more',
      },
      {
        area: 'pill text',
        level: 'strict',
        note: 'Keep it a short AI marker; do not reuse the badge for unrelated labels',
      },
    ],
  },
}
