/**
 * Generates `packages/eslint-plugin/src/prop-vocabulary.json` — the data the
 * `cascivo/prop-vocabulary` rule runs on.
 *
 * ## Why the rule is data-driven
 *
 * The 2026-08-21 report's sharpest finding was not any of its eleven defects; it was that
 * "the docs are doing work the API should eventually do itself". Most of that work moved into
 * the type system in this plan's Phase 2 — `label`/`ariaLabel` both compile now, `Switch` is
 * exported, `Field` takes `hint`. What is left is the class TypeScript structurally cannot
 * help with: a prop that does not exist produces a correct type error whose message teaches
 * nothing, so the adopter goes looking for the docs anyway.
 *
 * A lint rule can carry that message. Making it read one JSON file rather than hard-coding
 * cases means the next adopter report costs a row here instead of a paragraph in a guide —
 * which is the durable version of "it always was mentioned to be fixed".
 *
 * ## Why the rows are validated, not derived
 *
 * The pairing ("you probably wrote `tone`, the prop is `muted`") is a human judgement about
 * what someone would guess; nothing in the manifests encodes it. But both halves are
 * checkable, and a stale row is worse than no row — it teaches the wrong thing with the
 * authority of a fix list. So each row is asserted against `registry.json` here, at
 * generation time: the `is` prop must exist on that component and the `wrote` prop must not.
 * A rename on either side fails `pnpm regen` rather than shipping a lying rule.
 *
 * Foreign import names come from `packages/components/aliases.json`, minus any name
 * `@cascivo/react` actually exports — `Switch` is a real export now, so warning about it
 * would be wrong.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { reactExportedNames } from '../registry/react-exports.ts'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const OUT = join(ROOT, 'packages/eslint-plugin/src/prop-vocabulary.json')

interface PropRow {
  component: string
  wrote: string
  is: string
  note: string
  report: string
}
interface Source {
  props: PropRow[]
  numericProps: string[]
  tupleHooks: { hook: string; note: string; report: string }[]
  defaultDirection: { component: string; note: string; report: string }[]
}

const source = JSON.parse(
  readFileSync(join(ROOT, 'packages/eslint-plugin/near-misses.json'), 'utf8'),
) as Source

const registry = JSON.parse(readFileSync(join(ROOT, 'registry.json'), 'utf8')) as {
  components: { name: string; meta: { name: string; props?: { name: string }[] } }[]
}

function propsOf(displayName: string): Set<string> {
  const entry = registry.components.find((c) => c.meta.name === displayName)
  if (!entry) {
    throw new Error(
      `eslint-vocabulary: no registry entry named "${displayName}". Fix the row in ` +
        'packages/eslint-plugin/near-misses.json — a rule that names a component nobody ' +
        'ships is noise an adopter cannot act on.',
    )
  }
  return new Set((entry.meta.props ?? []).map((p) => p.name))
}

for (const row of source.props) {
  const props = propsOf(row.component)
  if (!props.has(row.is)) {
    throw new Error(
      `eslint-vocabulary: ${row.component} has no \`${row.is}\` prop, but near-misses.json ` +
        'tells adopters to use it. Update the row (or the component).',
    )
  }
  if (props.has(row.wrote)) {
    throw new Error(
      `eslint-vocabulary: ${row.component} now HAS \`${row.wrote}\`, so it is no longer a ` +
        'wrong guess. Delete the row from near-misses.json — warning about a prop that works ' +
        'is worse than saying nothing.',
    )
  }
}

for (const row of source.defaultDirection) propsOf(row.component)

// Foreign names worth flagging on import: those that do NOT resolve to a real export.
// `Switch` was the motivating case and is now exported, so it correctly drops out.
const exported = reactExportedNames(ROOT)
const imports: Record<string, string> = {}
const aliases = JSON.parse(
  readFileSync(join(ROOT, 'packages/components/aliases.json'), 'utf8'),
) as Record<string, string[] | string>
for (const [target, names] of Object.entries(aliases)) {
  if (target === '_comment' || !Array.isArray(names)) continue
  const entry = registry.components.find((c) => c.name === target)
  if (!entry) continue
  const real = entry.meta.name
  if (!exported.has(real)) continue
  for (const name of names) {
    // Only PascalCase spellings: `switch` is a keyword, not something anyone imports.
    if (!/^[A-Z]/.test(name) || exported.has(name) || name === real) continue
    imports[name] = real
  }
}

const out = {
  _comment:
    'GENERATED by scripts/eslint-vocabulary/generate.ts — edit packages/eslint-plugin/near-misses.json, then `pnpm regen`.',
  props: source.props,
  numericProps: source.numericProps,
  tupleHooks: source.tupleHooks,
  defaultDirection: source.defaultDirection,
  imports,
}
writeFileSync(OUT, `${JSON.stringify(out, null, 2)}\n`)
console.log(
  `eslint-vocabulary: ${source.props.length} prop rows, ${Object.keys(imports).length} foreign ` +
    `import names → ${OUT.slice(ROOT.length + 1)}`,
)
