#!/usr/bin/env node
/**
 * Pre-render email samples for the site.
 *
 * The site shows real, themed emails — not screenshots and not a mock. The obvious way to do
 * that is to import `@cascivo/email` into the site and render in the browser, and it is the
 * wrong way twice over: it would put `react-dom/server` and twelve resolved palettes into a
 * page bundle, and the site is Preact, so the renderer would have to be shimmed to run at
 * all.
 *
 * So the emails are rendered here, at build time, in Node, with real React — and the site
 * ships the finished HTML strings and drops them into an `<iframe srcdoc>`. What a visitor
 * sees is the exact output an adopter would send.
 *
 * It lives in this package rather than the repo's `scripts/` because it renders React, and
 * the root workspace deliberately carries none. It is still *invoked* from the root, which
 * works because Node resolves a dependency from the importing module's directory rather than
 * the working directory — so `packages/email/dist/index.js` finds React next to itself. It
 * writes into `apps/site`, the same cross-package direction `scripts/shims/generate.ts`
 * already takes.
 *
 * It imports the **built** package rather than the source: Node's type stripping does not
 * transform JSX, so importing `render.tsx` fails outright. `email:samples:generate` therefore
 * builds first — which also means the samples are generated from exactly what an adopter
 * installs.
 *
 * Run via `pnpm email:samples:generate` (and `pnpm regen`); drift-checked in CI.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createElement } from 'react'
import { readFileSync } from 'node:fs'
import {
  EMAIL_THEMES,
  indexFeatures,
  PasswordReset,
  passwordResetSubject,
  Receipt,
  receiptSubject,
  renderEmail,
  simulate,
  SIMULATED_CLIENTS,
  Welcome,
  welcomeSubject,
  type CanIEmailData,
} from '../dist/index.js'

const REPO_ROOT = join(import.meta.dirname, '..', '..', '..')
const OUT = join(REPO_ROOT, 'apps/site/src/marketing/email-samples.generated.ts')

const TEMPLATES = [
  {
    id: 'password-reset',
    name: 'Password reset',
    el: () => createElement(PasswordReset),
    subject: passwordResetSubject,
  },
  { id: 'welcome', name: 'Welcome', el: () => createElement(Welcome), subject: welcomeSubject },
  { id: 'receipt', name: 'Receipt', el: () => createElement(Receipt), subject: receiptSubject },
] as const

const features = indexFeatures(
  JSON.parse(
    readFileSync(join(REPO_ROOT, 'scripts/email/vendor/caniemail.json'), 'utf8'),
  ) as CanIEmailData,
)
const OUTLOOK = SIMULATED_CLIENTS.find((c) => c.platform === 'windows')!

interface Sample {
  html: string
  subject: string
  preheader: string
  encodedBytes: number
}

const samples: Record<string, Record<string, Sample>> = {}
const outlook: Record<string, string> = {}

for (const template of TEMPLATES) {
  samples[template.id] = {}
  for (const theme of EMAIL_THEMES) {
    const out = renderEmail(template.el(), { theme, subject: template.subject(), tier: 'strict' })
    samples[template.id]![theme] = {
      html: out.html,
      subject: out.subject,
      preheader: out.preheader ?? '',
      encodedBytes: out.stats.encodedBytes,
    }
  }
  // One simulated pass per template, in the light theme: the side-by-side that shows the
  // design surviving the client that supports the least.
  outlook[template.id] = simulate(samples[template.id]!['light']!.html, features, OUTLOOK)
}

const body = `// AUTO-GENERATED by scripts/site/generate-email-samples.ts — do not edit by hand.
// Run \`pnpm email:samples:generate\` (or \`pnpm regen\`) to refresh.
//
// Real \`@cascivo/email\` output, rendered at build time. The site drops these into an
// \`<iframe srcdoc>\`, so what a visitor sees is byte-for-byte what an adopter would send.

export interface EmailSample {
  html: string
  subject: string
  preheader: string
  /** Quoted-printable encoded size — what Gmail measures against its clip threshold. */
  encodedBytes: number
}

export const EMAIL_TEMPLATES = ${JSON.stringify(
  TEMPLATES.map((t) => ({ id: t.id, name: t.name })),
  null,
  2,
)} as const

export type EmailTemplateId = (typeof EMAIL_TEMPLATES)[number]['id']

/** template → theme → sample. */
export const EMAIL_SAMPLES: Record<string, Record<string, EmailSample>> = ${JSON.stringify(samples, null, 2)}

/**
 * The same emails with every declaration Outlook Windows does not support removed.
 *
 * Not a mock-up of Outlook — the real output, filtered by the Can I email support matrix.
 * Square button corners are the genuine degradation; everything else holds.
 */
export const EMAIL_OUTLOOK: Record<string, string> = ${JSON.stringify(outlook, null, 2)}
`

writeFileSync(OUT, body)

const bytes = Buffer.byteLength(body, 'utf8')
const { gzipSync } = await import('node:zlib')
console.log(
  `email samples: ${TEMPLATES.length} templates × ${EMAIL_THEMES.length} themes + ${TEMPLATES.length} simulated — ` +
    `${(bytes / 1024).toFixed(1)} KB raw, ${(gzipSync(body).length / 1024).toFixed(1)} KB gzip`,
)
