#!/usr/bin/env node
/**
 * Generate the email primitive reference — the per-component previews the site renders and
 * the markdown an agent reads.
 *
 * Two outputs, one source. `lib/gallery.ts` holds the examples as element trees and
 * `lib/primitive-props.ts` reads the props off the TypeScript, so neither surface carries a
 * transcribed copy of anything: the snippet is printed from the tree that was rendered, and
 * the props table is printed from the interface the compiler checks.
 *
 * It lives in this package rather than the repo's `scripts/` for the reason
 * `generate-site-samples.ts` states at length: it renders React, and the root workspace
 * carries none. It imports the **built** package, so the previews are produced by exactly
 * the code an adopter installs.
 *
 * Run via `pnpm email:primitives:generate` (and `pnpm regen`); drift-checked in CI.
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { gzipSync } from 'node:zlib'
import { createElement } from 'react'
import {
  Body,
  Container,
  EMAIL_THEMES,
  Head,
  Html,
  renderEmail,
  Section,
  type EmailTheme,
} from '../dist/index.js'

/**
 * The themes the primitive frames are rendered in — four of the twelve, on purpose.
 *
 * Every frame is a whole email document, so the module grows by roughly 60 KB per theme.
 * All twelve at once came to 734 KB of JavaScript for a reference page, and the twelve-theme
 * claim is already demonstrated end to end on `/docs/email`, where three complete templates
 * switch across the full set. These four cover the axes a primitive can
 * actually look wrong on: light, dark, a tinted light, and a high-contrast dark.
 */
const PREVIEW_THEMES = ['light', 'dark', 'warm', 'midnight'] as const
import { GALLERY, toJsx, type GalleryExample } from './lib/gallery.ts'
import { extractPrimitiveDocs, type PrimitiveProp } from './lib/primitive-props.ts'

const REPO_ROOT = join(import.meta.dirname, '..', '..', '..')
const SITE_OUT = join(REPO_ROOT, 'apps/site/src/marketing/email-previews.generated.ts')
const DOC_OUT = join(REPO_ROOT, 'docs/EMAIL-PRIMITIVES.md')
const DOC_URL = 'https://cascivo.com/docs/email/components'

const h = createElement

/** Wrap an example in the document its `frame` asks for. See `Frame` in `lib/gallery.ts`. */
function wrap(example: GalleryExample) {
  if (example.frame === 'raw') return example.el
  const inner =
    example.frame === 'bare'
      ? example.el
      : h(Container, null, h(Section, { padding: 24 }, example.el))
  return h(Html, null, h(Head, { title: example.title }), h(Body, null, inner))
}

const docs = extractPrimitiveDocs()

interface Preview {
  title: string
  description?: string
  code: string
  /** theme → the whole document, for an `<iframe srcdoc>`. */
  html: Record<string, string>
}

interface Primitive {
  name: string
  group: string
  description: string
  props: PrimitiveProp[]
  previews: Preview[]
}

const primitives: Primitive[] = GALLERY.map((entry) => {
  const doc = docs.get(entry.name)
  if (!doc) throw new Error(`gallery lists ${entry.name}, which has no <Name>Props interface`)

  return {
    name: entry.name,
    group: entry.group,
    description: doc.description,
    props: doc.props,
    previews: entry.examples.map((example) => {
      const document = wrap(example)
      const html: Record<string, string> = {}
      for (const theme of PREVIEW_THEMES) {
        html[theme] = renderEmail(document, {
          theme: theme as EmailTheme,
          subject: example.title,
        }).html
      }
      return {
        title: example.title,
        ...(example.description === undefined ? {} : { description: example.description }),
        code: toJsx(example.el),
        html,
      }
    }),
  }
})

/* ── the site module ─────────────────────────────────────────────────────────────────── */

const siteBody = `// AUTO-GENERATED by packages/email/scripts/generate-primitives.ts — do not edit by hand.
// Run \`pnpm email:primitives:generate\` (or \`pnpm regen\`) to refresh.
//
// Real \`@cascivo/email\` output, rendered at build time. The site drops each document into
// an \`<iframe srcdoc>\`: an email is a whole document with its own \`<body>\`, and a preview
// that inherited the docs stylesheet would be showing something no recipient will ever see.

export interface EmailPrimitiveProp {
  name: string
  type: string
  required: boolean
  default?: string
  description?: string
}

export interface EmailPrimitivePreview {
  title: string
  description?: string
  /** JSX printed from the very element tree that produced the frames below it. */
  code: string
  /** theme → the whole email document. */
  html: Record<string, string>
}

export interface EmailPrimitive {
  name: string
  group: string
  description: string
  props: EmailPrimitiveProp[]
  previews: EmailPrimitivePreview[]
}

/**
 * The themes these frames were rendered in.
 *
 * A subset of the twelve \`@cascivo/email\` ships — the generator states the byte budget
 * behind that. All twelve are demonstrated on complete templates at \`/docs/email\`.
 */
export const EMAIL_PREVIEW_THEMES = ${JSON.stringify(PREVIEW_THEMES)} as const

export const EMAIL_PRIMITIVES: EmailPrimitive[] = ${JSON.stringify(primitives, null, 2)}
`

writeFileSync(SITE_OUT, siteBody)

/* ── the markdown reference ──────────────────────────────────────────────────────────── */

const escapeCell = (text: string) => text.replace(/\|/g, '\\|').replace(/\n/g, ' ')

/**
 * The two props nearly every primitive takes.
 *
 * Stated once per surface rather than as twenty-two identical docstrings — a props table
 * whose `children` row repeats "The content" twenty-two times is noise, and a docstring
 * that says nothing still has to be read.
 */
const UNIVERSAL =
  'Every primitive below also takes `children` (its content) and `style` — inline ' +
  "declarations merged over the primitive's own, in camelCase, with lengths written in " +
  '`px`.'

function propsTable(props: PrimitiveProp[]): string[] {
  if (props.length === 0) return ['_No props._', '']
  return [
    '| Prop | Type | Default | Notes |',
    '| ---- | ---- | ------- | ----- |',
    ...props.map((prop) => {
      const name = prop.required ? `\`${prop.name}\` **(required)**` : `\`${prop.name}\``
      const fallback = prop.default ? `\`${prop.default}\`` : '—'
      return `| ${name} | \`${escapeCell(prop.type)}\` | ${fallback} | ${escapeCell(prop.description ?? '')} |`
    }),
    '',
  ]
}

const groups = [...new Set(primitives.map((p) => p.group))]

const lines: string[] = [
  '<!-- AUTO-GENERATED by packages/email/scripts/generate-primitives.ts — do not edit by hand. -->',
  '<!-- Run `pnpm email:primitives:generate` (or `pnpm regen`) to refresh. -->',
  '',
  '# Email primitives',
  '',
  `Every component \`@cascivo/email\` exports, with its props and a worked example. Live previews of`,
  `all ${primitives.length}, rendered as real email documents, are at [${DOC_URL}](${DOC_URL}). The`,
  `full set of ${EMAIL_THEMES.length} themes is demonstrated on complete templates at`,
  '[https://cascivo.com/docs/email](https://cascivo.com/docs/email).',
  '',
  'These are **not** the `@cascivo/react` components. HTML email is a separate render target:',
  'no flexbox, no grid, no custom properties, no `rem`, no client JavaScript. Layout is tables and',
  'styling is inline, because Outlook Windows still renders through Microsoft Word. See',
  '[RECIPE-EMAIL.md](./RECIPE-EMAIL.md) for the whole workflow and',
  '[EMAIL-CLIENT-SUPPORT.md](./EMAIL-CLIENT-SUPPORT.md) for what the conformance lint enforces.',
  '',
  '```tsx',
  "import { Body, Button, Container, Head, Html, Preview, Section, Text } from '@cascivo/email'",
  '```',
  '',
  UNIVERSAL,
  '',
  '## Contents',
  '',
]

for (const group of groups) {
  const names = primitives
    .filter((p) => p.group === group)
    .map((p) => `[\`${p.name}\`](#${p.name.toLowerCase()})`)
  lines.push(`- **${group}** — ${names.join(', ')}`)
}
lines.push('')

for (const group of groups) {
  lines.push(`## ${group}`, '')
  for (const primitive of primitives.filter((p) => p.group === group)) {
    lines.push(`### ${primitive.name}`, '', primitive.description, '')
    lines.push(...propsTable(primitive.props))
    for (const preview of primitive.previews) {
      lines.push(`**${preview.title}**`, '')
      if (preview.description) lines.push(preview.description, '')
      lines.push('```tsx', preview.code, '```', '')
    }
  }
}

writeFileSync(DOC_OUT, lines.join('\n'))

const frames = primitives.reduce((n, p) => n + p.previews.length, 0)
const bytes = Buffer.byteLength(siteBody, 'utf8')
console.log(
  `email primitives: ${primitives.length} components, ${frames} examples × ${PREVIEW_THEMES.length} themes — ` +
    `${(bytes / 1024).toFixed(1)} KB raw, ${(gzipSync(siteBody).length / 1024).toFixed(1)} KB gzip`,
)
