/**
 * Generates a per-component `index.ts` barrel in every registry source directory.
 *
 * ## Why
 *
 * `cascivo add` writes `src/components/ui/<name>/<name>.tsx`, so every import an adopter
 * writes is `…/components/ui/card/card` — the name twice. A dashboard vendoring ~45
 * components carries ~45 of those lines. Six of 132 directories already shipped an
 * `index.ts`, which is worse than none: it teaches an expectation the other 126 break.
 *
 * ## Why generated rather than hand-written
 *
 * A hand-kept barrel is a second list of a module's exports, and second lists drift — the
 * Mechanism-B failure this repo keeps hitting. `export *` has no list to drift: it always
 * re-exports exactly what the module exports, values and types alike.
 *
 * Run: `pnpm barrels:generate` (part of `pnpm regen`).
 */
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(HERE, '..', '..')

/** Roots whose subdirectories are copy-paste components. */
const ROOTS = [
  join(REPO_ROOT, 'packages', 'components', 'src'),
  join(REPO_ROOT, 'packages', 'components', 'src', 'brand'),
  join(REPO_ROOT, 'packages', 'layouts', 'src'),
]

/** Directories that are not components — they group them (see ROOTS) or hold helpers. */
const SKIP = new Set(['test-utils', 'blocks', 'sections', 'brand'])

const BANNER = '// Generated by scripts/registry/barrels.ts — run `pnpm regen`. Do not edit.\n'

/** Modules in a component directory whose exports belong in the barrel. */
async function barrelSources(dir: string): Promise<string[]> {
  const files = await readdir(dir)
  return files
    .filter((f) => /\.tsx?$/.test(f))
    .filter((f) => !/\.(test|stories|meta)\.tsx?$/.test(f))
    .filter((f) => !f.endsWith('.d.ts'))
    .filter((f) => f !== 'index.ts' && f !== 'index.tsx')
    .sort()
    .map((f) => f.replace(/\.tsx?$/, ''))
}

/** True when the module has at least one export — an empty `export *` is a type error. */
async function hasExports(dir: string, mod: string): Promise<boolean> {
  for (const ext of ['.tsx', '.ts']) {
    try {
      return /^export /m.test(await readFile(join(dir, mod + ext), 'utf8'))
    } catch {
      /* try the next extension */
    }
  }
  return false
}

let written = 0
for (const root of ROOTS) {
  let entries: Awaited<ReturnType<typeof readdir>>
  try {
    entries = await readdir(root, { withFileTypes: true } as never)
  } catch {
    continue
  }
  for (const entry of entries as unknown as { name: string; isDirectory(): boolean }[]) {
    if (!entry.isDirectory() || SKIP.has(entry.name)) continue
    const dir = join(root, entry.name)
    const mods: string[] = []
    for (const mod of await barrelSources(dir)) {
      if (await hasExports(dir, mod)) mods.push(mod)
    }
    if (mods.length === 0) continue

    const body = mods.map((m) => `export * from './${m}'`).join('\n')
    const next = `${BANNER}${body}\n`
    const path = join(dir, 'index.ts')
    let current = ''
    try {
      current = await readFile(path, 'utf8')
    } catch {
      /* new barrel */
    }
    // Never clobber a hand-written barrel that predates this generator with a narrower
    // named-export list — those were deliberate. Only rewrite what this script owns.
    if (current !== '' && !current.startsWith(BANNER)) continue
    if (current === next) continue
    await writeFile(path, next, 'utf8')
    written++
  }
}

console.log(`barrels: wrote ${written} index.ts file(s)`)
