/**
 * Snapshot every published `@cascivo/*` version into the CLI as a generated module.
 *
 * `cascivo create` used to write `"latest"` for all four cascivo dependencies. That is the
 * loosest possible specifier on a set of independently-versioned 0.x packages, and it
 * directly contradicts GETTING-STARTED.md's own instruction to "pin **exact** versions (no
 * `^`) and watch `breaking-changes.json`". A scaffolded app could resolve a
 * `@cascivo/react` and a `@cascivo/themes` published weeks apart.
 *
 * The CLI ships standalone, so it cannot read the workspace at runtime — the versions have
 * to be baked in, the same way `@cascivo/docs` snapshots them into `content/versions.json`
 * at build time.
 *
 * Run: part of `pnpm regen` (`pnpm cli-versions:generate`).
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('../..', import.meta.url))
const PACKAGES = join(ROOT, 'packages')
const OUT = join(PACKAGES, 'cli/src/generated/versions.ts')

/** Packages a scaffolded app may depend on, in the order `create` writes them. */
const SCAFFOLD_DEPS = [
  '@cascivo/react',
  '@cascivo/themes',
  '@cascivo/charts',
  '@cascivo/icons',
  '@cascivo/eslint-config',
]

interface PackageJson {
  name?: string
  version?: string
  private?: boolean
  peerDependencies?: Record<string, string>
}

function readPackages(): Map<string, PackageJson> {
  const out = new Map<string, PackageJson>()
  for (const dir of readdirSync(PACKAGES)) {
    let pkg: PackageJson
    try {
      pkg = JSON.parse(readFileSync(join(PACKAGES, dir, 'package.json'), 'utf8')) as PackageJson
    } catch {
      continue
    }
    if (pkg.name !== undefined && pkg.private !== true) out.set(pkg.name, pkg)
  }
  return out
}

const packages = readPackages()

const entries: string[] = []
for (const name of SCAFFOLD_DEPS) {
  const version = packages.get(name)?.version
  if (version === undefined) throw new Error(`cli-versions: ${name} is missing or private`)
  entries.push(`  '${name}': '${version}',`)
}

/**
 * The signals peer floor, read from `@cascivo/core` rather than restated. `peer-floors`
 * already asserts this is `>=3.0.0`; duplicating the literal here would let the two drift.
 */
const signalsFloor = packages.get('@cascivo/core')?.peerDependencies?.['@preact/signals-react']
if (signalsFloor === undefined) {
  throw new Error('cli-versions: @cascivo/core does not declare a @preact/signals-react peer')
}

const banner = `// GENERATED by scripts/registry/cli-versions.ts — do not edit by hand.
/**
 * Exact published versions, baked in at build time.
 *
 * Scaffolded apps pin these rather than \`"latest"\`: the cascivo packages version
 * independently on 0.x, so a floating specifier can resolve a mutually incompatible set,
 * and GETTING-STARTED.md tells adopters to pin exactly. Regenerate with \`pnpm regen\`.
 */
`

writeFileSync(
  OUT,
  `${banner}export const CASCIVO_VERSIONS: Record<string, string> = {
${entries.join('\n')}
}

/** \`@cascivo/core\`'s declared \`@preact/signals-react\` peer range. */
export const SIGNALS_PEER = '${signalsFloor}'
`,
)

console.log(`cli-versions: wrote ${SCAFFOLD_DEPS.length} pinned versions to ${OUT}`)
