// Generated by @cascivo/app/vite from the routes directory — do not edit.
// Add, rename or delete a route file and this file is rewritten.
import { lazyRoute } from '@cascivo/app'
import type { Route } from '@cascivo/app'

export const routes: Route[] = [
  lazyRoute('/board', () => import('./routes/board')),
  lazyRoute('/reports', () => import('./routes/reports')),
  lazyRoute('/settings', () => import('./routes/settings')),
  lazyRoute('/', () => import('./routes/index')),
]

export const notFound: Route | undefined = lazyRoute('*', () => import('./routes/404'))

/** Every route pattern. Fill one with `buildPath` for a typed link. */
export type AppPath = '/board' | '/reports' | '/settings' | '/'
