// Generated by scripts/shims/generate.ts — do not edit. Run `pnpm regen`.
//
// The site is Preact and the components are React, so it cannot compile against their
// sources; it re-exports the built declarations instead, which carry the real types and
// have no JSX bodies to check. See the generator for the full rationale.

export {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from '../../../../packages/react/dist/index'
