#!/usr/bin/env node
/**
 * Resolve every cascivo theme to a flat, email-safe palette.
 *
 * Emits `packages/email/src/tokens/palettes.generated.ts` — twelve palettes of literal
 * values, `oklch()` and `var()` both gone. This is the file `renderEmail({ theme })` reads,
 * and it is committed so the package has no build-time dependency on the theme CSS.
 *
 * It also supersedes the hand-copied `BASE_LIGHT` / `BASE_DARK` blocks in
 * `packages/theme-kit/src/css.ts` as the way resolved values are obtained — those remain
 * because they serve a different consumer (the CSS generator, which still emits `oklch()`),
 * but no new hand-copied resolution should be added anywhere.
 *
 * Run via `pnpm email:palettes:generate` (and `pnpm regen`); drift-checked in CI.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { buildPalette } from '../../packages/email/src/tokens/resolve.ts'

const REPO_ROOT = join(import.meta.dirname, '..', '..')
const TOKENS_CSS = join(REPO_ROOT, 'packages/tokens/src/index.css')
const THEMES_DIR = join(REPO_ROOT, 'packages/themes/src')

/**
 * The themes `@cascivo/themes` ships, in the order its own description lists them.
 * `base`, `all`, `light-dark` and `tailwind` are excluded deliberately: they are
 * aggregates or adapters, not themes an email can be rendered in.
 */
export const EMAIL_THEMES = [
  'light',
  'dark',
  'warm',
  'flat',
  'minimal',
  'midnight',
  'pastel',
  'brutalist',
  'corporate',
  'terminal',
  'cyberpunk',
  'arcade',
] as const

export type EmailTheme = (typeof EMAIL_THEMES)[number]

/**
 * Single-quoted, oxfmt-style. `JSON.stringify` would emit double quotes, and the repo's
 * formatter would rewrite them on the next `vp check --fix` — so `pnpm regen` followed by
 * a format would leave a diff and the drift check would fail on a clean tree.
 */
function quote(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`
}

function generate(): string {
  const tokensCss = readFileSync(TOKENS_CSS, 'utf8')
  const entries = EMAIL_THEMES.map((theme) => {
    const themeCss = readFileSync(join(THEMES_DIR, `${theme}.css`), 'utf8')
    const palette = buildPalette(tokensCss, themeCss)
    const body = Object.entries(palette)
      .map(([k, v]) => `    '${k}': ${quote(v)},`)
      .join('\n')
    return `  ${theme}: {\n${body}\n  },`
  }).join('\n')

  return `// AUTO-GENERATED by scripts/email/generate-palettes.ts — do not edit by hand.
// Run \`pnpm email:palettes:generate\` (or \`pnpm regen\`) to refresh.
//
// Every cascivo theme, flattened for email: \`var()\` chains followed to literals and
// \`oklch()\` gamut-mapped to sRGB hex. Translucent colours are composited against their
// own theme's background, because no email client composites alpha dependably.

/** A theme flattened to literal values, keyed by custom-property name. */
export type Palette = Readonly<Record<string, string>>

export const PALETTES = {
${entries}
} as const satisfies Record<string, Palette>

/** The themes an email can be rendered in. */
export type EmailTheme = keyof typeof PALETTES

export const EMAIL_THEMES = Object.keys(PALETTES) as EmailTheme[]
`
}

const out = join(REPO_ROOT, 'packages/email/src/tokens/palettes.generated.ts')
writeFileSync(out, generate())
console.log(`email: wrote ${EMAIL_THEMES.length} palettes to ${out.replace(`${REPO_ROOT}/`, '')}`)
