#!/usr/bin/env node
/**
 * Generate `docs/EMAIL-CLIENT-SUPPORT.md` from the vendored Can I email snapshot.
 *
 * Hand-written client-support tables rot: upstream retests a client, the doc keeps the old
 * verdict, and an adopter designs against a claim that stopped being true. Deriving the
 * table from the same data the conformance lint consults makes the doc and the gate
 * incapable of disagreeing.
 *
 * Run via `pnpm email:support:generate` (and `pnpm regen`); drift-checked in CI.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  DEFAULT_FLOOR,
  indexFeatures,
  verdict,
  type CanIEmailData,
} from '../../packages/email/src/conformance/support.ts'
import { CASCIVO_ALLOW } from '../../packages/email/src/conformance/lint.ts'

const REPO_ROOT = join(import.meta.dirname, '..', '..')
const SNAPSHOT = join(REPO_ROOT, 'scripts/email/vendor/caniemail.json')

const data = JSON.parse(readFileSync(SNAPSHOT, 'utf8')) as CanIEmailData & {
  $source: string
  api_version: string
  last_update_date: string
}
const features = indexFeatures(data)

/**
 * The features an adopter asks about. Chosen because each one either shapes the primitive
 * set or is something a designer reaches for and needs to be told not to.
 */
const REPORTED: { slug: string; label: string }[] = [
  { slug: 'css-display-flex', label: 'Flexbox' },
  { slug: 'css-display-grid', label: 'CSS Grid' },
  { slug: 'css-gap', label: '`gap`' },
  { slug: 'css-variables', label: 'Custom properties (`var()`)' },
  { slug: 'css-modern-color', label: '`oklch()` / `lab()`' },
  { slug: 'css-function-color-mix', label: '`color-mix()`' },
  { slug: 'css-unit-rem', label: '`rem` units' },
  { slug: 'css-border-radius', label: '`border-radius`' },
  { slug: 'css-box-shadow', label: '`box-shadow`' },
  { slug: 'css-at-media', label: '`@media`' },
  { slug: 'css-at-media-prefers-color-scheme', label: '`prefers-color-scheme`' },
  { slug: 'html-svg', label: 'Inline SVG' },
  { slug: 'css-position', label: '`position`' },
  { slug: 'css-float', label: '`float`' },
  { slug: 'css-padding', label: '`padding`' },
  { slug: 'css-background-color', label: '`background-color`' },
  { slug: 'css-border-collapse', label: '`border-collapse`' },
  { slug: 'css-vertical-align', label: '`vertical-align`' },
  { slug: 'html-table', label: '`<table>`' },
]

const SYMBOL = { ok: '✅', caveat: '⚠️', blocked: '❌', untested: '—' } as const

function row(slug: string, label: string): string {
  const cells = DEFAULT_FLOOR.map((client) => {
    const v = verdict(features, slug, [client])
    return SYMBOL[v.level]
  })
  const overall = verdict(features, slug)
  return `| ${label} | ${SYMBOL[overall.level]} | ${cells.join(' | ')} |`
}

const header = ['Feature', 'Verdict', ...DEFAULT_FLOOR.map((c) => c.label)]

const md = `<!-- AUTO-GENERATED by scripts/email/generate-support-doc.ts — do not edit by hand. -->
<!-- Run \`pnpm email:support:generate\` (or \`pnpm regen\`) to refresh. -->

# Email client support

What \`@cascivo/email\` can and cannot use, derived from the [Can I email](https://www.caniemail.com)
support matrix rather than asserted by hand. This page and the conformance lint read the same
data, so they cannot disagree.

**Snapshot:** Can I email api ${data.api_version}, tested ${data.last_update_date}.
Refresh with \`pnpm email:caniemail:refresh\` and commit the diff.

## How to read the verdict

| Symbol | Meaning |
| --- | --- |
| ✅ | Supported by every client in the floor. |
| ⚠️ | Partial in at least one client — usually "works on a table cell, not a div". Allowed, and enforced by structural invariants rather than by feature support. |
| ❌ | Not supported by at least one client. The lint blocks it. |
| — | Not in the matrix. Foundational HTML like \`<td>\` and \`<a>\` lands here; it is not a failure. |

## The support floor

A feature must work in all of these for \`@cascivo/email\` to use it:

${DEFAULT_FLOOR.map((c) => `- ${c.label}`).join('\n')}

Outlook (Windows) is the binding constraint. It renders with the Word engine, it fails most
modern CSS, and it is the one client that **cannot be tested in-house** — no emulator exists.
It is in the floor precisely for that reason: the lint is what stands between the generator
and a broken Outlook render.

## Feature support

| ${header.join(' | ')} |
| ${header.map(() => '---').join(' | ')} |
${REPORTED.map(({ slug, label }) => row(slug, label)).join('\n')}

## Accepted exceptions

A blocked feature may still be used when its absence **degrades rather than breaks** — the
email stays legible, correct and actionable in the client that lacks it. This is the whole
list:

${Object.entries(CASCIVO_ALLOW)
  .map(([slug, reason]) => `### \`${slug}\`\n\n${reason}`)
  .join('\n\n')}

## What this does not tell you

The matrix reports feature support. It does not reproduce a client's own rendering quirks,
and no offline tool can: the Word engine is a proprietary Windows binary with no emulator.
That residual is bought down by construction — the primitive set is built so it cannot emit
what Outlook lacks — plus a release-time manual pass. See
\`docs/specs/email-target.md\` §4.2 and §5.
`

writeFileSync(join(REPO_ROOT, 'docs/EMAIL-CLIENT-SUPPORT.md'), md)
console.log(`email: wrote docs/EMAIL-CLIENT-SUPPORT.md (${REPORTED.length} features)`)
