/**
 * Generates `docs/internal/feedback/RECURRENCE.md` from `recurrence.json`.
 *
 * ## Why a finding-level ledger exists
 *
 * The README's status hygiene binds a *plan's* status to what actually shipped. It cannot
 * see the failure mode twelve adopter reports kept hitting, because that one lives BETWEEN
 * plans: a finding is closed in plan N, and re-reported in plan N+2, without either plan
 * ever being dishonest about itself.
 *
 * The rule this ledger enforces (in scripts/checks/recurrence.test.ts) is one line:
 * **a finding may not be marked closed without naming a guard that exists.** "Fixed in
 * source" is not a closure. A fix with nothing holding it in place is exactly what produced
 * the recurrence.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..', '..')
const DIR = join(ROOT, 'docs', 'internal', 'feedback')

export interface RecurrenceFinding {
  id: string
  title: string
  reports: string[]
  plans: string[]
  mechanism: string
  guard: string | null
  status: 'open' | 'closed'
  note?: string
  guardNote?: string
}

export interface RecurrenceData {
  findings: RecurrenceFinding[]
}

export async function loadRecurrence(): Promise<RecurrenceData> {
  return JSON.parse(await readFile(join(DIR, 'recurrence.json'), 'utf8')) as RecurrenceData
}

/** `feedback-tanstack-start-adopter-2026-07-18.md` → `07-18`. */
function shortDate(file: string): string {
  return /(\d{4})-(\d{2}-\d{2})\.md$/.exec(file)?.[2] ?? file.replace(/\.md$/, '')
}

function render(data: RecurrenceData): string {
  const findings = [...data.findings].sort(
    (a, b) => b.reports.length - a.reports.length || a.id.localeCompare(b.id),
  )
  const open = findings.filter((f) => f.status === 'open')
  const closed = findings.filter((f) => f.status === 'closed')

  const row = (f: RecurrenceFinding) => {
    const reports = f.reports.map(shortDate).join(', ')
    const guard = f.guard ? `\`${f.guard}\`` : '**none**'
    const why = f.guard ? (f.note ?? '') : (f.guardNote ?? '')
    return `| ${f.title} | ${f.reports.length} (${reports}) | ${f.mechanism} | ${guard} | ${why} |`
  }

  return `<!-- GENERATED by scripts/feedback/recurrence.ts — edit recurrence.json, not this file. -->

# Recurrence ledger

Finding-level tracking, one row per defect an adopter reported. The README tracks **plans**;
findings recur **across** plans, which plan granularity structurally cannot see.

## The rule

> **A finding may not be marked closed without naming a guard that exists.**

"Fixed in source" is not a closure. A fix with nothing holding it in place is precisely what
produced twelve reports of the same handful of defects. If no guard can express the
invariant, the finding stays **open** with a note saying why, and every subsequent plan lists
it.

\`scripts/checks/recurrence.test.ts\` enforces this: a \`closed\` row whose guard is missing,
empty, or does not resolve to a real npm script or file fails CI. It also fails when a
\`feedback-*.md\` report exists that no row references — a new report must be triaged into
this table, not just filed.

## Open — ${open.length}

| Finding | Reports | Mech. | Guard | Why still open |
| --- | --- | --- | --- | --- |
${open.map(row).join('\n')}

## Closed — ${closed.length}

Each row names the guard that makes it stay closed.

| Finding | Reports | Mech. | Guard | How it holds |
| --- | --- | --- | --- | --- |
${closed.map(row).join('\n')}

## Mechanisms

Defined in [\`README.md\`](README.md). Briefly: **A** a claim that exists only as prose ·
**B** a fact hand-authored instead of derived from source · **C** one fact with several
owners · **D** a fix that landed on one surface only · **E** only observable in a
consumer-shaped environment · **F** the guard re-implements the adopter's tool instead of
running it.
`
}

const data = await loadRecurrence()
await writeFile(join(DIR, 'RECURRENCE.md'), render(data), 'utf8')
console.log(`recurrence: wrote RECURRENCE.md (${data.findings.length} findings)`)
