import React from 'react'
import type { Decorator } from '@storybook/react-vite'

/**
 * "Copy AI context" — embeds a copyable, component-tailored system-prompt
 * snippet into every Storybook story. A developer handing a section off to
 * Cursor/Copilot can click once to copy a prompt that pins the model to this
 * component's tokens, container breakpoints, and the design system's rules.
 *
 * The prompts are generated by `scripts/context/generate.ts` into
 * `public/context-prompts.json` (keyed by component name) and fetched at runtime.
 */

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '')

let promptsByKey: Map<string, string> | null = null

async function loadPrompts(): Promise<Map<string, string>> {
  if (promptsByKey) return promptsByKey
  const map = new Map<string, string>()
  try {
    const res = await fetch('/context-prompts.json')
    if (res.ok) {
      const data = (await res.json()) as Record<string, string>
      for (const [name, prompt] of Object.entries(data)) map.set(norm(name), prompt)
    }
  } catch {
    // No prompts available — the button will report it on click.
  }
  promptsByKey = map
  return map
}

/** Derive the component key from a story title like "Inputs/Button". */
function inferKey(title: string | undefined): string | null {
  if (!title) return null
  const last = title.split('/').pop() ?? ''
  return norm(last) || null
}

function flash(btn: HTMLButtonElement, message: string, original: string): void {
  btn.textContent = message
  window.setTimeout(() => {
    btn.textContent = original
  }, 1500)
}

const LABEL = 'Copy AI context'

function CopyContextButton({ storyKey }: { storyKey: string }) {
  const onClick = async (e: React.MouseEvent<HTMLButtonElement>) => {
    const btn = e.currentTarget
    const map = await loadPrompts()
    const prompt = map.get(storyKey)
    if (!prompt) {
      flash(btn, 'No AI context for this component', LABEL)
      return
    }
    try {
      await navigator.clipboard.writeText(prompt)
      flash(btn, '✓ Copied AI context', LABEL)
    } catch {
      flash(btn, 'Copy failed', LABEL)
    }
  }
  return (
    <button
      type="button"
      onClick={onClick}
      title="Copy a tailored system-prompt snippet for this component"
      style={{
        font: 'inherit',
        fontSize: '0.75rem',
        padding: '0.25rem 0.625rem',
        borderRadius: 'var(--cascivo-radius-button, 0.375rem)',
        border: '1px solid var(--cascivo-color-border, #d4d4d8)',
        background: 'var(--cascivo-color-surface, #fafafa)',
        color: 'var(--cascivo-color-text, #18181b)',
        cursor: 'pointer',
      }}
    >
      {LABEL}
    </button>
  )
}

export const withContextPrompt: Decorator = (Story, context) => {
  const key = inferKey(context.title)
  return (
    <>
      <Story />
      {key && (
        <div
          style={{
            marginBlockStart: '1rem',
            paddingBlockStart: '0.5rem',
            borderBlockStart: '1px dashed var(--cascivo-color-border, #d4d4d8)',
          }}
        >
          <CopyContextButton storyKey={key} />
        </div>
      )}
    </>
  )
}
