// Generated by scripts/recipes/blocks.ts — run `pnpm recipes:blocks`. Do not edit.

/** The registry blocks a blueprint page can render (`cascivo create --from`), with what each shows. */
export const BLUEPRINT_BLOCKS: ReadonlyMap<string, string> = new Map([
  ['auth-login', 'Email + password login with remember-me checkbox and forgot-password link.'],
  ['auth-signup', 'Full-name, email, password, confirm-password sign-up form with terms checkbox.'],
  [
    'dashboard-overview',
    'Welcome header with four KPI stat cards (revenue, users, orders, conversion).',
  ],
  ['dashboard-table', 'Searchable, sortable, paginated data table with export button.'],
  [
    'faq',
    'Frequently-asked-questions section composed from the Accordion component, with a centered, readable measure.',
  ],
  [
    'marketing-features',
    'Three-column responsive feature grid with icon, title, and description per cell.',
  ],
  ['marketing-hero', 'Full-width hero with headline, subtitle, CTA pair, and trust badges.'],
  [
    'pricing',
    'Responsive three-tier pricing section composed from Card, Badge, and Button, with a highlighted featured plan.',
  ],
  ['settings-profile', 'Two-section settings form: personal info fields + preference toggles.'],
  [
    'site-footer',
    'Multi-column site footer composed from Link and Separator, with a brand blurb, link columns, and a legal row.',
  ],
  [
    'testimonials',
    'Responsive testimonial grid composed from Card and Avatar, with a quote and attribution per card.',
  ],
  ['dashboard-charts', 'Dashboard layout with KPI tiles, line chart, bar chart, and pie chart.'],
  ['empty-dashboard', 'Dashboard page showing an empty state with a call-to-action button.'],
  ['login-page', 'Authentication login page with email and password form.'],
  ['notification-center', 'A list of notification alerts with a mark-all-read action.'],
  ['page-with-breadcrumb', 'A centered content page with a breadcrumb navigation and page header.'],
  ['settings-form-page', 'Settings page with profile form inside a two-column settings layout.'],
  ['stats-cards', 'Grid of KPI stat cards with trend badges.'],
  ['users-table-page', 'Full users management page with table, search, and invite action.'],
])
