import type { ArmId } from './arms.ts'
import type { AgentUsage } from './result.ts'
import type { Score } from './score.ts'

export interface RunRecord {
  prompt: string
  arm: ArmId
  run: number
  /** Null in a dry run, where no model was called. */
  usage: AgentUsage | null
  score: Score
}

export interface BenchResults {
  date: string
  model: string | null
  dryRun: boolean
  runs: RunRecord[]
}

function median(values: number[]): number | null {
  if (values.length === 0) return null
  const sorted = [...values].sort((a, b) => a - b)
  const mid = Math.floor(sorted.length / 2)
  return sorted.length % 2 ? sorted[mid]! : (sorted[mid - 1]! + sorted[mid]!) / 2
}

const fmt = (n: number | null, digits = 0) =>
  n === null ? '—' : n.toLocaleString('en-US', { maximumFractionDigits: digits })

/** Every input token the model read: billed, cached-written and cached-read. */
const totalInput = (u: AgentUsage) => u.inputTokens + u.cacheCreationTokens + u.cacheReadTokens

/** One row per prompt and arm, medians over its runs: the table docs/BENCHMARKS.md publishes. */
export function markdownTable(results: BenchResults): string {
  const rows: string[] = [
    '| Prompt | Arm | Runs | Input tokens | Output tokens | Cost (USD) | Wall time (s) | Turns | `tsc` errors | Audit errors | Audit warnings |',
    '| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |',
  ]
  const keys = [...new Set(results.runs.map((r) => `${r.prompt}\u0000${r.arm}`))]
  for (const key of keys) {
    const [prompt, arm] = key.split('\u0000') as [string, ArmId]
    const runs = results.runs.filter((r) => r.prompt === prompt && r.arm === arm)
    const usages = runs.flatMap((r) => (r.usage ? [r.usage] : []))
    const of = (pick: (s: Score) => number | null) =>
      median(runs.flatMap((r) => (pick(r.score) === null ? [] : [pick(r.score)!])))
    const noApp = runs.filter((r) => r.score.app === null).length
    rows.push(
      [
        prompt,
        arm,
        `${runs.length}${noApp ? ` (${noApp} no app)` : ''}`,
        fmt(median(usages.map(totalInput))),
        fmt(median(usages.map((u) => u.outputTokens))),
        fmt(median(usages.map((u) => u.costUsd)), 2),
        fmt(median(usages.map((u) => u.durationMs / 1000)), 1),
        fmt(median(usages.map((u) => u.turns))),
        fmt(of((s) => s.tscErrors)),
        fmt(of((s) => s.auditErrors)),
        fmt(of((s) => s.auditWarnings)),
      ]
        .join(' | ')
        .replace(/^/, '| ')
        .concat(' |'),
    )
  }
  return rows.join('\n')
}

/** docs/AGENT-BENCHMARKS.md, generated from one real run's results. */
export function publishedDoc(results: BenchResults, source: string): string {
  return `# Agent benchmark

> Generated by \`pnpm --filter bench-agent bench --publish\`: do not edit. Method:
> \`apps/bench/agent/README.md\`. Raw results: \`${source}\`.

What an agent spends to build an app with cascivo, by surface. Every row is the median of its
runs; each run starts from an empty directory with the cascivo MCP server and \`claude -p\`
headless, and is scored on what it leaves: \`tsc --noEmit\` errors and \`cascivo audit --ai\`
findings (warnings include those in the registry blocks a blueprint copies).

- **today**: \`create_app\` for the shell, then every page written as TSX.
- **blueprints**: also \`list_blocks\` and \`compose_app\`, so pages can be registry blocks.

| | |
| --- | --- |
| Date | ${results.date.slice(0, 10)} |
| Model | ${results.model ?? 'the CLI default'} |

${markdownTable(results)}
`
}
