/**
 * The docs site's type shims stay generated, and stay free of escape hatches.
 *
 * ## Why
 *
 * `apps/site` is Preact and the components are React, so it cannot compile against the
 * component sources — `tsc` would check their JSX bodies under Preact's attribute types and
 * reject the signal bindings they rely on. `tsconfig.json` therefore maps every
 * `@cascivo/components/*` specifier to a `.d.ts` under `src/shims/`.
 *
 * Hand-written, those were a second copy of the public API that only a human kept in sync,
 * and at 1.0 they went stale: `dropdown.d.ts` still declared the removed `separator` flag,
 * six more still declared the removed value-carrying `onChange`, and **50 of 67 ended in
 * `[key: string]: unknown`**, which switches off excess-property checking altogether. The
 * site compiled clean against props that no longer existed, and against chart series whose
 * shape was wrong in two different ways.
 *
 * They are now generated by `scripts/shims/generate.ts` as one-line re-exports of the built
 * declarations, so the types are the real ones and there is nothing to keep in sync.
 * `pnpm shims:check` proves the committed files match the generator. This file guards the
 * two properties that check cannot express on its own:
 *
 *  1. **No escape hatches.** A catch-all index signature or a bare `unknown` prop bag makes
 *     the site accept anything, which is the failure mode that hid all of the above.
 *  2. **Nothing hand-written creeps back.** A shim that declares its own props is one that
 *     will drift; the generator's output never does.
 *
 * `blocks.d.ts` is exempt from the generated-shape rule: it is a `declare module` wildcard
 * for the dynamically-imported block subpaths, not a component re-export. It is still held to
 * rule 1.
 */
import assert from 'node:assert/strict'
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { describe, it } from 'node:test'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('../..', import.meta.url))
const SHIM_DIR = join(ROOT, 'apps/site/src/shims')

/** Not a component re-export — a wildcard module declaration for lazy block imports. */
const WILDCARD_SHIMS = new Set(['blocks.d.ts'])

const shims = readdirSync(SHIM_DIR)
  .filter((f) => f.endsWith('.d.ts'))
  .map((file) => ({ file, source: readFileSync(join(SHIM_DIR, file), 'utf8') }))

describe('site shims', () => {
  it('finds the shims it is meant to cover (guards against passing vacuously)', () => {
    assert.ok(shims.length >= 60, `expected 60+ shims, found ${shims.length}`)
  })

  it('no shim weakens type checking with a catch-all or an unknown prop bag', () => {
    const offenders = shims
      .filter(({ source }) =>
        /\[\s*key\s*:\s*string\s*\]|:\s*Record<string, unknown>|props:\s*any/.test(source),
      )
      .map(({ file }) => `  apps/site/src/shims/${file}`)
    assert.deepEqual(
      offenders,
      [],
      'A catch-all index signature turns off excess-property checking, so the site will ' +
        'compile against props that do not exist — which is exactly how the removed ' +
        '`Dropdown.separator` flag stayed in the published docs demo through a full green ' +
        `CI run.\n${offenders.join('\n')}`,
    )
  })

  it('every component shim is generated, not hand-written', () => {
    const offenders = shims
      .filter(({ file }) => !WILDCARD_SHIMS.has(file))
      .filter(({ source }) => !source.startsWith('// Generated by scripts/shims/generate.ts'))
      .map(({ file }) => `  apps/site/src/shims/${file}`)
    assert.deepEqual(
      offenders,
      [],
      'These shims are hand-written. Declare nothing here: run `pnpm shims:generate` so the ' +
        'file re-exports the built declarations instead, and the site gets the real types ' +
        `with nothing to keep in sync.\n${offenders.join('\n')}`,
    )
  })
})
