// Hand-maintained: the subset of @cascivo/react components <CascivoView /> can render
// by name. Add an import + a `componentMap` entry to expose a new component to the
// render engine. (No generator writes this file.)
import type React from 'react'
import {
  Accordion,
  Alert,
  AutoGrid,
  Avatar,
  AvatarGroup,
  Badge,
  Blockquote,
  Breadcrumb,
  Button,
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
  Center,
  Checkbox,
  CheckboxCard,
  Code,
  Columns,
  Combobox,
  CommandMenu,
  DataTable,
  DatePicker,
  Dropdown,
  EmptyState,
  FileUploader,
  Flex,
  Form,
  Grid,
  GridItem,
  Header,
  HeaderPanel,
  Heading,
  Image,
  Input,
  InputGroup,
  Kbd,
  LargeTitleHeader,
  Link,
  List,
  ListItem,
  Modal,
  NumberInput,
  OverflowMenu,
  PageHeader,
  Pagination,
  Progress,
  ProgressBar,
  ProgressIndicator,
  Radio,
  RadioCard,
  RadioCardGroup,
  Search,
  Select,
  Separator,
  ShellHeader,
  SideNav,
  Skeleton,
  Slider,
  Spacer,
  Spinner,
  Stat,
  Status,
  Steps,
  Switcher,
  Tabs,
  Tag,
  Text,
  Textarea,
  TimePicker,
  Timeline,
  ToastProvider,
  Toggle,
  Tooltip,
} from '@cascivo/react'

type AnyComponent = React.ComponentType<Record<string, unknown>>
const cast = (c: unknown) => c as AnyComponent

export const componentMap: Record<string, AnyComponent> = {
  Accordion: cast(Accordion),
  Alert: cast(Alert),
  AutoGrid: cast(AutoGrid),
  Avatar: cast(Avatar),
  AvatarGroup: cast(AvatarGroup),
  Badge: cast(Badge),
  Blockquote: cast(Blockquote),
  Breadcrumb: cast(Breadcrumb),
  Button: cast(Button),
  Card: cast(Card),
  CardContent: cast(CardContent),
  CardFooter: cast(CardFooter),
  CardHeader: cast(CardHeader),
  CardTitle: cast(CardTitle),
  Center: cast(Center),
  Checkbox: cast(Checkbox),
  CheckboxCard: cast(CheckboxCard),
  Code: cast(Code),
  Columns: cast(Columns),
  Combobox: cast(Combobox),
  CommandMenu: cast(CommandMenu),
  DataTable: cast(DataTable),
  DatePicker: cast(DatePicker),
  Dropdown: cast(Dropdown),
  EmptyState: cast(EmptyState),
  FileUploader: cast(FileUploader),
  Flex: cast(Flex),
  Form: cast(Form),
  Grid: cast(Grid),
  GridItem: cast(GridItem),
  Header: cast(Header),
  HeaderPanel: cast(HeaderPanel),
  Heading: cast(Heading),
  Image: cast(Image),
  Input: cast(Input),
  InputGroup: cast(InputGroup),
  Kbd: cast(Kbd),
  LargeTitleHeader: cast(LargeTitleHeader),
  Link: cast(Link),
  List: cast(List),
  ListItem: cast(ListItem),
  Modal: cast(Modal),
  NumberInput: cast(NumberInput),
  OverflowMenu: cast(OverflowMenu),
  PageHeader: cast(PageHeader),
  Pagination: cast(Pagination),
  Progress: cast(Progress),
  ProgressBar: cast(ProgressBar),
  ProgressIndicator: cast(ProgressIndicator),
  Radio: cast(Radio),
  RadioCard: cast(RadioCard),
  RadioCardGroup: cast(RadioCardGroup),
  Search: cast(Search),
  Select: cast(Select),
  Separator: cast(Separator),
  ShellHeader: cast(ShellHeader),
  SideNav: cast(SideNav),
  Skeleton: cast(Skeleton),
  Slider: cast(Slider),
  Spacer: cast(Spacer),
  Spinner: cast(Spinner),
  Stat: cast(Stat),
  Status: cast(Status),
  Steps: cast(Steps),
  Switcher: cast(Switcher),
  Tabs: cast(Tabs),
  Tag: cast(Tag),
  Text: cast(Text),
  Textarea: cast(Textarea),
  TimePicker: cast(TimePicker),
  Timeline: cast(Timeline),
  Toast: cast(ToastProvider),
  Toggle: cast(Toggle),
  Tooltip: cast(Tooltip),
}
