// generated — do not edit (scripts/schema/generate.ts)
import type React from 'react'
import {
  Accordion,
  Alert,
  Avatar,
  Badge,
  Breadcrumb,
  Button,
  Card,
  Checkbox,
  Combobox,
  CommandMenu,
  DataTable,
  DatePicker,
  Dropdown,
  EmptyState,
  FileUploader,
  Form,
  Header,
  HeaderPanel,
  Input,
  InputGroup,
  Kbd,
  Link,
  Modal,
  NumberInput,
  OverflowMenu,
  Pagination,
  ProgressBar,
  ProgressIndicator,
  Radio,
  Search,
  Select,
  Separator,
  ShellHeader,
  SideNav,
  Skeleton,
  Slider,
  Spinner,
  Switcher,
  RadioCard,
  RadioCardGroup,
  CheckboxCard,
  Tabs,
  Tag,
  Textarea,
  TimePicker,
  ToastProvider,
  Toggle,
  Tooltip,
} from '@cascivo/react'

type AnyComponent = React.ComponentType<Record<string, unknown>>
const cast = (c: unknown) => c as AnyComponent

export const componentMap: Record<string, AnyComponent> = {
  Accordion: cast(Accordion),
  Alert: cast(Alert),
  Avatar: cast(Avatar),
  Badge: cast(Badge),
  Breadcrumb: cast(Breadcrumb),
  Button: cast(Button),
  Card: cast(Card),
  Checkbox: cast(Checkbox),
  Combobox: cast(Combobox),
  CommandMenu: cast(CommandMenu),
  DataTable: cast(DataTable),
  DatePicker: cast(DatePicker),
  Dropdown: cast(Dropdown),
  EmptyState: cast(EmptyState),
  FileUploader: cast(FileUploader),
  Form: cast(Form),
  Header: cast(Header),
  HeaderPanel: cast(HeaderPanel),
  Input: cast(Input),
  InputGroup: cast(InputGroup),
  Kbd: cast(Kbd),
  Link: cast(Link),
  Modal: cast(Modal),
  NumberInput: cast(NumberInput),
  OverflowMenu: cast(OverflowMenu),
  Pagination: cast(Pagination),
  ProgressBar: cast(ProgressBar),
  ProgressIndicator: cast(ProgressIndicator),
  Radio: cast(Radio),
  Search: cast(Search),
  Select: cast(Select),
  Separator: cast(Separator),
  ShellHeader: cast(ShellHeader),
  SideNav: cast(SideNav),
  Skeleton: cast(Skeleton),
  Slider: cast(Slider),
  Spinner: cast(Spinner),
  Switcher: cast(Switcher),
  RadioCard: cast(RadioCard),
  RadioCardGroup: cast(RadioCardGroup),
  CheckboxCard: cast(CheckboxCard),
  Tabs: cast(Tabs),
  Tag: cast(Tag),
  Textarea: cast(Textarea),
  TimePicker: cast(TimePicker),
  Toast: cast(ToastProvider),
  Toggle: cast(Toggle),
  Tooltip: cast(Tooltip),
}
